SwRandoms::RandomBase2 Class Reference
#include <Random3.h>
Public Member Functions
RandomBase2 (unsigned long Dimensionality_)
unsigned long GetDimensionality () const
virtual RandomBase2 * clone () const =0
virtual void GetUniforms (SwArrays::MyArray &variates)=0
virtual void Skip (unsigned long numberOfPaths)=0
virtual void SetSeed (unsigned long Seed)=0
virtual void Reset ()=0
Private Attributes
unsigned long Dimensionality
Detailed Description
Definition at line 9 of file Random3.h.
Constructor & Destructor Documentation
SwRandoms::RandomBase2::RandomBase2 (unsigned long Dimensionality_) [inline]
Definition at line 12 of file Random3.h.
12 : Dimensionality( Dimensionality_ ) {};
Member Function Documentation
unsigned long SwRandoms::RandomBase2::GetDimensionality () const [inline]
Definition at line 26 of file Random3.h.
References Dimensionality.
Referenced by SwRandoms::RandSobol::GetUniforms(), SwRandoms::RandDrand48::GetUniforms(), SwRandoms::RandSobol::Skip(), and SwRandoms::RandDrand48::Skip().
27 {
28   return Dimensionality;
29 }
virtual RandomBase2* SwRandoms::RandomBase2::clone () const [pure virtual]
Implemented in SwRandoms::RandDrand48 , and SwRandoms::RandSobol .
virtual void SwRandoms::RandomBase2::GetUniforms (SwArrays::MyArray & variates) [pure virtual]
Implemented in SwRandoms::RandDrand48 , and SwRandoms::RandSobol .
virtual void SwRandoms::RandomBase2::Skip (unsigned long numberOfPaths) [pure virtual]
Implemented in SwRandoms::RandDrand48 , and SwRandoms::RandSobol .
virtual void SwRandoms::RandomBase2::SetSeed (unsigned long Seed) [pure virtual]
Implemented in SwRandoms::RandDrand48 , and SwRandoms::RandSobol .
virtual void SwRandoms::RandomBase2::Reset () [pure virtual]
Implemented in SwRandoms::RandDrand48 , and SwRandoms::RandSobol .
Member Data Documentation
unsigned long SwRandoms::RandomBase2::Dimensionality [private]
Definition at line 23 of file Random3.h.
Referenced by GetDimensionality().
The documentation for this class was generated from the following file:
Gyulassy/opacity3/src/randoms/Random3.h