SwRandoms::RandDrand48 Class Reference
#include <RandDrand.h>
Public Member Functions
RandDrand48 (unsigned long Dimensionality, unsigned long Seed=1)
virtual RandomBase2 * clone () const
virtual void GetUniforms (SwArrays::MyArray &variates)
virtual void Skip (unsigned long numberOfPaths)
virtual void SetSeed (unsigned long Seed)
virtual void Reset ()
Private Attributes
unsigned long InitialSeed
Detailed Description
Definition at line 9 of file RandDrand.h.
Constructor & Destructor Documentation
SwRandoms::RandDrand48::RandDrand48 (unsigned long Dimensionality, unsigned long Seed = 1)
Definition at line 8 of file RandDrand.cpp.
Referenced by clone().
9   : RandomBase2(Dimensionality), InitialSeed( Seed )
10 {
11 
12 }
Member Function Documentation
RandomBase2 * SwRandoms::RandDrand48::clone () const [virtual]
Implements SwRandoms::RandomBase2 .
Definition at line 14 of file RandDrand.cpp.
References RandDrand48().
15 {
16   return new RandDrand48( *this );
17 }
void SwRandoms::RandDrand48::GetUniforms (SwArrays::MyArray & variates) [virtual]
Implements SwRandoms::RandomBase2 .
Definition at line 19 of file RandDrand.cpp.
References SwRandoms::RandomBase2::GetDimensionality().
Referenced by Skip().
20 {
21   for (unsigned long j=0; j<GetDimensionality(); j++)
22     variates[j] = drand48();
23 }
void SwRandoms::RandDrand48::Skip (unsigned long numberOfPaths) [virtual]
Implements SwRandoms::RandomBase2 .
Definition at line 25 of file RandDrand.cpp.
References SwRandoms::RandomBase2::GetDimensionality(), and GetUniforms().
26 {
27   SwArrays::MyArray tmp( GetDimensionality() );
28   for (unsigned long j=0; j<numberOfPaths; j++)
29     GetUniforms(tmp);
30 }
void SwRandoms::RandDrand48::SetSeed (unsigned long Seed) [virtual]
Implements SwRandoms::RandomBase2 .
Definition at line 32 of file RandDrand.cpp.
References InitialSeed.
33 {
34   InitialSeed = Seed;
35   srand48( Seed );
36 }
void SwRandoms::RandDrand48::Reset () [virtual]
Implements SwRandoms::RandomBase2 .
Definition at line 38 of file RandDrand.cpp.
References InitialSeed.
39 {
40   srand48( InitialSeed );
41 }
Member Data Documentation
unsigned long SwRandoms::RandDrand48::InitialSeed [private]
Definition at line 21 of file RandDrand.h.
Referenced by Reset(), and SetSeed().
The documentation for this class was generated from the following files:
Gyulassy/opacity3/src/randoms/RandDrand.h
Gyulassy/opacity3/src/randoms/RandDrand.cpp