UniformFunction Class Reference
#include <Function.h>
Public Member Functions
UniformFunction (unsigned long Dimensionality)
virtual ~UniformFunction ()
virtual Function * clone () const
virtual void function (MyArray &xs, MyArray &res)
virtual void NormedIntegralInverse (MyArray &xs, MyArray &res)
virtual void SetParams (MyArray &params_)
Detailed Description
Definition at line 69 of file Function.h.
Constructor & Destructor Documentation
UniformFunction::UniformFunction (unsigned long Dimensionality)
Definition at line 64 of file Function.cpp.
Referenced by clone().
65   : Function( Dimensionality )
66 {
67 
68 }
UniformFunction::~UniformFunction () [virtual]
Definition at line 70 of file Function.cpp.
71 {
72 
73 }
Member Function Documentation
Function * UniformFunction::clone () const [virtual]
Implements Function .
Definition at line 75 of file Function.cpp.
References UniformFunction().
76 {
77   return new UniformFunction(*this);
78 }
void UniformFunction::function (MyArray & xs, MyArray & res) [virtual]
Implements Function .
Definition at line 80 of file Function.cpp.
References Function::GetDimensionality(), and Function::GetRange().
81 {
82   for (unsigned long i=0; i<GetDimensionality(); ++i)
83   {
84     res[i] = 1. / GetRange(i);
85   }
86 }
void UniformFunction::NormedIntegralInverse (MyArray & xs, MyArray & res) [virtual]
Implements Function .
Definition at line 88 of file Function.cpp.
References Function::GetDimensionality(), Function::GetRange(), and Function::GetXmin().
89 {
90   for (unsigned long i=0; i<GetDimensionality(); ++i)
91   {
92     xs[i] = GetXmin(i) + uniforms[i]*GetRange(i);
93   }
94 }
void UniformFunction::SetParams (MyArray & params_) [virtual]
Implements Function .
Definition at line 96 of file Function.cpp.
97 {
98 
99 }
The documentation for this class was generated from the following files:
Gyulassy/opacity3/src/glv1/Function.h
Gyulassy/opacity3/src/glv1/Function.cpp