UnitStepFunction Class Reference
#include <Function.h>
Public Member Functions
UnitStepFunction (unsigned long Dimensionality)
virtual ~UnitStepFunction ()
virtual Function * clone () const
virtual void function (MyArray &xs, MyArray &res)
virtual void NormedIntegralInverse (MyArray &xs, MyArray &res)
virtual void SetParams (MyArray &params_)
Private Attributes
MyArray steps
Detailed Description
Definition at line 85 of file Function.h.
Constructor & Destructor Documentation
UnitStepFunction::UnitStepFunction (unsigned long Dimensionality)
Definition at line 104 of file Function.cpp.
Referenced by clone().
105   : Function( Dimensionality ), steps( Dimensionality )
106 {
107 
108 }
UnitStepFunction::~UnitStepFunction () [virtual]
Definition at line 110 of file Function.cpp.
111 {
112 
113 }
Member Function Documentation
Function * UnitStepFunction::clone () const [virtual]
Implements Function .
Definition at line 115 of file Function.cpp.
References UnitStepFunction().
116 {
117   return new UnitStepFunction(*this);
118 }
void UnitStepFunction::function (MyArray & xs, MyArray & res) [virtual]
Implements Function .
Definition at line 120 of file Function.cpp.
References Function::GetDimensionality(), Function::GetXmin(), and steps.
121 {
122   for (unsigned long i=0; i<GetDimensionality(); ++i)
123   {
124     xs[i] < steps[i]  ? res[i] = 1. / (steps[i]-GetXmin(i))  : res[i] = 0.;
125   }
126 }
void UnitStepFunction::NormedIntegralInverse (MyArray & xs, MyArray & res) [virtual]
Implements Function .
Definition at line 128 of file Function.cpp.
References Function::GetDimensionality(), Function::GetXmin(), and steps.
129 {
130   for (unsigned long i=0; i<GetDimensionality(); ++i)
131   {
132     xs[i] = GetXmin(i) + uniforms[i]*steps[i];
133   }
134 }
void UnitStepFunction::SetParams (MyArray & params_) [virtual]
Implements Function .
Definition at line 136 of file Function.cpp.
References steps.
137 {
138   steps = steps_;
139 }
Member Data Documentation
MyArray UnitStepFunction::steps [private]
Definition at line 98 of file Function.h.
Referenced by function(), NormedIntegralInverse(), and SetParams().
The documentation for this class was generated from the following files:
Gyulassy/opacity3/src/glv1/Function.h
Gyulassy/opacity3/src/glv1/Function.cpp