Parameters Class Reference
#include <parameters.h>
Public Member Functions
Parameters (std::string StringID_)
int ParseInputFile (std::string FileName)
int ParseSingleLine (std::string LineString)
Helper function for ParseInputFile - does one line supplied as LineString.
std::list< std::string > GetParametersString (std::string ParamID)
Get a specific parameter in the map, identified by ParamID.
std::vector< double > GetParametersDouble (std::string ParamID)
Get the parameter set, but then convert to a vector of doubles.
std::vector< long > GetParametersLong (std::string ParamID)
Get the parameter set, but then convert to a vector of longs.
int CheckForUnaccessedParameters ()
int WriteToFile (std::string FileName, bool append)
Private Attributes
std::string StringID
The unique ID to identify the settings section in the file.
std::map< std::string, std::list< std::string > > TheParameters
The map in which to store ParamID, list of parameters.
std::map< std::string, bool > AccessedList
The map in which to store whether ParamID has been accessed.
Detailed Description
Parameters: reads a file, retrieves and stores the settings in a map structure When we want to retrieve that setting, a call to GetParameters with the relevant ParamID returns a list of strings containing the relevant parameters.
The file format: the file can contain anything. This object only looks at lines between `# Begin settings for ` + StringID, and `# End settings for ` + StringID where StringID was supplied to the constructor of the object. Between these lines, blank lines and lines beginning with # (comment lines) are ignored. The rest are taken as `ParamID param1 param2 ...`, space separated values.
ParseInputFile returns an integer. If this is > 0, then this specifies the number of settings lines that have been read. If < 0, this gives an error code. = 0 is also an error - no settings read in.
TODO: extend so that multiple files can be read in, where subsequent files are specified by a line `+ ./furtherparams.txt` line. Must check for looping references. This would be useful for eg multiple jet energies and types, but where everything else is the same. One common settings file, one specialized.
Author: Simon Wicks <simon_wicks@yahoo.com>
Definition at line 31 of file parameters.h.
Constructor & Destructor Documentation
Parameters::Parameters (std::string StringID_)
Member Function Documentation
int Parameters::ParseInputFile (std::string FileName)
Read in a file which contains all the settings for the run
Parameters:
FileName The filename to process
Returns: Integer error code
Referenced by Driver< TcalcEngine, Tstore, numOfRandoms >::Setup().
int Parameters::ParseSingleLine (std::string LineString)
Helper function for ParseInputFile - does one line supplied as LineString.
std::list<std::string> Parameters::GetParametersString (std::string ParamID)
Get a specific parameter in the map, identified by ParamID.
Referenced by RadCalcer::RadCalcer(), GlvRadiative3< TqperpGenerate, TqperpCalculate, numOfRandoms >::SetParameters(), and Driver< TcalcEngine, Tstore, numOfRandoms >::SetParameters().
std::vector<double> Parameters::GetParametersDouble (std::string ParamID)
Get the parameter set, but then convert to a vector of doubles.
Referenced by RadCalcer::RadCalcer(), Store2D::SetParameters(), GlvRadiative3< TqperpGenerate, TqperpCalculate, numOfRandoms >::SetParameters(), and ZposGenerator::ZposGenerator().
std::vector<long> Parameters::GetParametersLong (std::string ParamID)
Get the parameter set, but then convert to a vector of longs.
Referenced by RadCalcer::RadCalcer(), and GlvRadiative3< TqperpGenerate, TqperpCalculate, numOfRandoms >::SetParameters().
int Parameters::CheckForUnaccessedParameters ()
See whether all the parameters read in from file have been accessed by the program
Returns: Gives 0 if all parameters used, otherwise gives the number of unaccessed parameters (ie >0)
Definition at line 190 of file parameters.cpp.
References AccessedList.
Referenced by Driver< TcalcEngine, Tstore, numOfRandoms >::Setup().
191 {
192   // How many unaccessed parameters have we found so far
193   int ReturnValue = 0;
194 
195   // Now iterate over all parameters in the map
196   // (the ParamIDs in AccessedList should be the same as in TheParameters)
197   for ( map<string, bool>::iterator i = AccessedList.begin();
198         i != AccessedList.end(); ++i )
199   {
200     if ( i->second != true )
201     {
202       ++ReturnValue;
203       cerr << "Unused parameter: " << i->first << "\n";
204     }
205   }
206 
207   return ReturnValue;
208 }
int Parameters::WriteToFile (std::string FileName, bool append)
Write our parameters to file, for record and possible reopening later
Parameters:
FileName The filename of the file to write to
append A true / false flag on whether to erase the current contents of the file of to append to it.
Returns: Integer error code, 0 if ok
Referenced by Driver< TcalcEngine, Tstore, numOfRandoms >::SaveResults().
Member Data Documentation
std::string Parameters::StringID [private]
The unique ID to identify the settings section in the file.
Definition at line 65 of file parameters.h.
std::map<std::string, std::list<std::string> > Parameters::TheParameters [private]
The map in which to store ParamID, list of parameters.
Definition at line 67 of file parameters.h.
std::map<std::string, bool> Parameters::AccessedList [private]
The map in which to store whether ParamID has been accessed.
Definition at line 69 of file parameters.h.
Referenced by CheckForUnaccessedParameters().
The documentation for this class was generated from the following files:
Gyulassy/opacity3/src/parameters.h
Gyulassy/opacity3/src/parameters.cpp