Driver< TcalcEngine, Tstore, numOfRandoms > Class Template Reference
#include <driver.h>
Public Member Functions
Driver ()
~Driver ()
int Setup (std::string resume, std::string inputFile)
void SetParameters (Parameters &myParameters)
Read any runtime parameters for the Driver object from the Parameters object.
void RunOneIteration ()
Run a single iteration of the monte carlo simulation.
void SaveResults (std::string outputFile)
Save the stored results to a file.
Private Attributes
TcalcEngine calculator
Supplied template parameter type, to perform the calculation.
Tstore storage
Supplied template parameter type, to store the results of the calculation.
Parameters myParameters
Object to read runtime parameters from file, supplied to calculation and storage.
Wrapper< SwRandoms::RandomBase2 > randomGenerator
Random number generator, on the interval [0,1).
Detailed Description
template<typename TcalcEngine, typename Tstore, std::size_t numOfRandoms> class Driver< TcalcEngine, Tstore, numOfRandoms >
Author: Simon Wicks <simonw@phys.columbia.edu> A generic driver for a Monte Carlo calculation At run time, different random number generator can be used: for example pseudorandoms such as standard drand48(); quasirandoms such as Sobol sequences (the latter can vastly increase the rate of convergence of Monte Carlo integration).
Template parameters: TcalcEngine, Tstore, numOfRandoms TcalcEngine is an object that performs the calculation, with the interface .SetParameters(Parameters inParams) .SetRandoms(boost::array<numOfRandoms> randomNumbers) .SetCoord(long coord, double value) .GetAnswer(std::vector answers) Tstore is an object in which to keep the results, with the interface .SetParameters(Parameters inParams) .AddPoint(long dim1, long dim2, std::vector<double> result) .WriteToFile(std::string filename, bool appendToFile) numOfRandoms is the number of random numbers to be used in the simulation
TODO: add the number of dimensions of the result as a template parameter, generalize the iteration over deterministic dimensions to be n-dimensional add this number of deterministic dimensions as a template parameter
TODO: add multithreading, so that multiple calculation engines can be run in parallel while adding into the same data store
Definition at line 47 of file driver.h.
Constructor & Destructor Documentation
template<typename TcalcEngine, typename Tstore, std::size_t numOfRandoms> Driver< TcalcEngine, Tstore, numOfRandoms >::Driver () [inline]
Definition at line 77 of file driver.h.
78   : myParameters( "Opacity3" )
79 {
80   // Nothing to do on creation, most setup done by the Setup() function
81   // so that errors on setup can be understood
82 
83   // The only thing is the constructor of myParameters,
84   // to tell it that the version of this program is Opacity version 3
85   // TODO: make the 'Opacity3' section describe all necessary parts of the program
86   // for a compatible read in / out
87 }
template<typename TcalcEngine, typename Tstore, std::size_t numOfRandoms> Driver< TcalcEngine, Tstore, numOfRandoms >::~Driver () [inline]
Definition at line 90 of file driver.h.
91 {
92   // Nothing to do in the destructor
93 }
Member Function Documentation
template<typename TcalcEngine, typename Tstore, std::size_t numOfRandoms> int Driver< TcalcEngine, Tstore, numOfRandoms >::Setup (std::string resume, std::string inputFile) [inline]
Setup routine - read in runtime parameters, set up all objects as necessary =`y` to resume from a previous run, =`n` to start a new one Filename of a) previous run file if resuming (including runtime parameters on the end), or b) runtime parameters file if not resuming
Definition at line 96 of file driver.h.
References Driver< TcalcEngine, Tstore, numOfRandoms >::calculator, Parameters::CheckForUnaccessedParameters(), Driver< TcalcEngine, Tstore, numOfRandoms >::myParameters, Parameters::ParseInputFile(), Driver< TcalcEngine, Tstore, numOfRandoms >::SetParameters(), and Driver< TcalcEngine, Tstore, numOfRandoms >::storage.
97 {
98   // Function to do all necessary run time setup of objects
99   // TODO: give a meaningful return code, so if this fails the program quits
100 
101   // The runtime settings are read in from a file with a specific format
102   // This format is governed by the 'Parameters' object, see there for specifics
103 
104   // First, read in the file into the object
105   // If we are resuming from a previous run, the parameters have been written to the
106   // end of the file, and the Parameters objects can find them there
107   // All the tokens in the file are read into a 'map'
108   myParameters.ParseInputFile( inputFile );
109 
110   // Pass the parameters object to each object in turn
111   // First, this one, the driver
112   SetParameters( myParameters );
113   // Second, the storage object - eg for size of each dimensions, number of points etc 
114   storage.SetParameters( myParameters );
115   // Third, the calculation object - eg GLV specific params, mu, temperature etc
116   calculator.SetParameters( myParameters );
117 
118   // If we are resuming from a previous run, we also need to read in the statistics
119   // from that run into the data store
120   if ( resume == "y" )
121     storage.ReadFromFile( inputFile );
122 
123   // Finally, check that all the inputs from the parameters file were used at some point
124   // Otherwise, the user might think that some parameters are being set that really aren't
125   int allUsed = myParameters.CheckForUnaccessedParameters();
126   if ( allUsed != 0 )
127   {
128     std::cerr << "Driver::Setup - " << allUsed << " unused parameters from input file.\n";
129     return 1;
130   }
131   else
132   {
133     std::cout << "All parameters read successfully from " << inputFile << std::endl;
134   }
135 
136   // TODO: change this so that more errors are detected and so more possible to not
137   // return 0
138   return 0;
139 }
template<typename TcalcEngine, typename Tstore, std::size_t numOfRandoms> void Driver< TcalcEngine, Tstore, numOfRandoms >::SetParameters (Parameters & myParameters) [inline]
Read any runtime parameters for the Driver object from the Parameters object.
Definition at line 142 of file driver.h.
References Parameters::GetParametersString(), and Driver< TcalcEngine, Tstore, numOfRandoms >::randomGenerator.
Referenced by Driver< TcalcEngine, Tstore, numOfRandoms >::Setup().
143 {
144   // Do specific setup for this driver object
145   // The only settings necessary are for the random number generator
146   // TODO: clean up the 'Parameters' object, so this doesn't look so convoluted
147 
148   std::list<std::string> ReturnedParamsString;
149   
150   // The type of random number generator
151   // Current options are 'Drand48' and 'Sobol'
152   ReturnedParamsString.empty();
153   ReturnedParamsString = MyParameters.GetParametersString( "@RandomNumberGenerator" );
154   
155   SwRandoms::RandDrand48 ranDrand48( numOfRandoms );
156   SwRandoms::RandSobol ranSobol( numOfRandoms );
157 
158   if ( ReturnedParamsString.front() == "Drand48" )
159     randomGenerator = ranDrand48;
160   else if ( ReturnedParamsString.front() == "Sobol" )
161     randomGenerator = ranSobol;
162   else
163   {
164     //return -1;
165   }
166 
167   // Now that we have set up the type of generator, we need a seed for the
168   // generator
169   // TODO: add this as an option to the Parameters object, including the time(NULL) option
170   //long seed = time(NULL);
171   long seed = 2;
172   randomGenerator->SetSeed( seed );
173 
174   //return 0;
175 }
template<typename TcalcEngine, typename Tstore, std::size_t numOfRandoms> void Driver< TcalcEngine, Tstore, numOfRandoms >::RunOneIteration () [inline]
Run a single iteration of the monte carlo simulation.
Definition at line 178 of file driver.h.
References Driver< TcalcEngine, Tstore, numOfRandoms >::calculator, Driver< TcalcEngine, Tstore, numOfRandoms >::randomGenerator, and Driver< TcalcEngine, Tstore, numOfRandoms >::storage.
179 {
180   // The guts of the Monte Carlo calculation
181   // For one iteration, we fetch in a set of random numbers,
182   // (these are supplied as a uniform distribution over [0,1)
183   // then pass this to the calculation object,
184   // (which will transform them to the required limits)
185   // then iterate over all the points in the deterministic dimensions,
186   // getting the calculation result for each point,
187   // and passing this result to the data store.
188   // TODO: generalize the iteration over deterministic dimensions to n-dimensions,
189   // with n chosen as a template parameter to the driver object
190 
191   // First, get the array of random numbers
192   // TODO: change the interface to the random number generator
193   // to ask / get a fixed size array using boost::array
194   // At the moment, the change from a boost::array to a std::vector (MyArray)
195   // is cumbersome / a hack
196   boost::array<double, numOfRandoms> randomNumbers;
197   SwArrays::MyArray randomNumbersTmp( numOfRandoms );
198   randomGenerator->GetUniforms( randomNumbersTmp );
199   for ( std::size_t i=0; i<numOfRandoms; ++i )
200     randomNumbers[i] = randomNumbersTmp[i];
201 
202   // Pass the random numbers to the calculator object
203   calculator.SetRandoms( randomNumbers );
204 
205   // Now iterate over the deterministic dimensions,
206   // setting the new coordinate for each point in each dimension,
207   // getting the answer and adding it to the data store
208   // TODO: improve, to have arbitrary number of dimensions
209   std::vector<double> tmp(1);
210   for (long dim1=0; dim1<storage.GetLengthDim1(); ++dim1)
211   {
212     calculator.SetCoord( 1, storage.GetCoordDim1( dim1 ) );
213 
214     for (long dim2=0; dim2<storage.GetLengthDim2(); ++dim2)
215     {
216       calculator.SetCoord( 2, storage.GetCoordDim2( dim2 ) );
217       calculator.GetAnswer( tmp );
218       storage.AddPoint( dim1, dim2, tmp );
219     }
220   }
221 }
template<typename TcalcEngine, typename Tstore, std::size_t numOfRandoms> void Driver< TcalcEngine, Tstore, numOfRandoms >::SaveResults (std::string outputFile) [inline]
Save the stored results to a file.
Definition at line 224 of file driver.h.
References Driver< TcalcEngine, Tstore, numOfRandoms >::myParameters, Driver< TcalcEngine, Tstore, numOfRandoms >::storage, and Parameters::WriteToFile().
225 {
226   // Save the results of our simulation to a permanent file
227   // We need to include the state of both the data store and
228   // the input runtime parameters
229 
230   // First, send the Store2D to file
231   // The false here => erase any current contents of the file
232   storage.WriteToFile( outputFile, false );
233 
234   // Now delegate to the params class to output the settings to the end of the file
235   // In this way, we have a record of what the inputs were, and a way to resume and
236   // add more statistics if wanted.
237   // The true here => append to file
238   myParameters.WriteToFile( outputFile, true );
239 }
Member Data Documentation
template<typename TcalcEngine, typename Tstore, std::size_t numOfRandoms> TcalcEngine Driver< TcalcEngine, Tstore, numOfRandoms >::calculator [private]
Supplied template parameter type, to perform the calculation.
Definition at line 51 of file driver.h.
Referenced by Driver< TcalcEngine, Tstore, numOfRandoms >::RunOneIteration(), and Driver< TcalcEngine, Tstore, numOfRandoms >::Setup().
template<typename TcalcEngine, typename Tstore, std::size_t numOfRandoms> Tstore Driver< TcalcEngine, Tstore, numOfRandoms >::storage [private]
Supplied template parameter type, to store the results of the calculation.
Definition at line 53 of file driver.h.
Referenced by Driver< TcalcEngine, Tstore, numOfRandoms >::RunOneIteration(), Driver< TcalcEngine, Tstore, numOfRandoms >::SaveResults(), and Driver< TcalcEngine, Tstore, numOfRandoms >::Setup().
template<typename TcalcEngine, typename Tstore, std::size_t numOfRandoms> Parameters Driver< TcalcEngine, Tstore, numOfRandoms >::myParameters [private]
Object to read runtime parameters from file, supplied to calculation and storage.
Definition at line 55 of file driver.h.
Referenced by Driver< TcalcEngine, Tstore, numOfRandoms >::SaveResults(), and Driver< TcalcEngine, Tstore, numOfRandoms >::Setup().
template<typename TcalcEngine, typename Tstore, std::size_t numOfRandoms> Wrapper<SwRandoms::RandomBase2> Driver< TcalcEngine, Tstore, numOfRandoms >::randomGenerator [private]
Random number generator, on the interval [0,1).
Definition at line 57 of file driver.h.
Referenced by Driver< TcalcEngine, Tstore, numOfRandoms >::RunOneIteration(), and Driver< TcalcEngine, Tstore, numOfRandoms >::SetParameters().
The documentation for this class was generated from the following file:
Gyulassy/opacity3/src/driver.h