StatGathering::StatisticsMean Class Reference
#include <statisticsmc.h>
Public Member Functions
StatisticsMean ()
virtual StatisticsMC * clone () const
clone method, to interface with the 'Wrapper' template
virtual void AddOneResult (double result)
virtual void AddOneSetOfResults (long Number_, std::vector< std::vector< double > > &ResultsSoFar_)
virtual void Reset ()
Reset all internal values to zero.
virtual void SetResultsSoFar (long Number_, std::vector< std::vector< double > > &ResultsSoFar_)
Set to a specific set of results.
virtual std::vector< std::vector< double > > GetResultsSoFar () const
Private Attributes
double RunningSum
The sum of all the input results.
double RunningSum2
The sum of all the squares of input results.
unsigned long PathsDone
The total number of points input.
Friends
std::ostream & operator<< (std::ostream &out, const StatisticsMean &stats)
friend to << so that we can overload the << operator to output a ConvergenceTable object
std::istream & operator>> (std::istream &in, StatisticsMean &stats)
Detailed Description
A simple implementation of a statistics gatherer Keeps a running tab on the total sum of results and the sum of results^2 The results: 1D vector - the mean, the standard deviation
Definition at line 63 of file statisticsmc.h.
Constructor & Destructor Documentation
StatGathering::StatisticsMean::StatisticsMean ()
Definition at line 8 of file statisticsmc.cpp.
Referenced by clone().
9   : RunningSum(0.), RunningSum2(0.), PathsDone(0)
10 {
11 
12 }
Member Function Documentation
StatisticsMC * StatGathering::StatisticsMean::clone () const [virtual]
clone method, to interface with the 'Wrapper' template
Implements StatGathering::StatisticsMC .
Definition at line 68 of file statisticsmc.cpp.
References StatisticsMean().
69 {
70   return new StatisticsMean(*this);
71 }
void StatGathering::StatisticsMean::AddOneResult (double result) [virtual]
Add one result to the mix This is the standard way of adding in another result
Implements StatGathering::StatisticsMC .
Definition at line 14 of file statisticsmc.cpp.
References PathsDone, RunningSum, and RunningSum2.
15 {
16   // Adding in one result
17   // Hence, increment PathsDone by one, add the result to the running sum,
18   // add the squre to RunningSum2
19   PathsDone++;
20   RunningSum += result;
21   RunningSum2 += result*result;
22 }
void StatGathering::StatisticsMean::AddOneSetOfResults (long Number_, std::vector< std::vector< double > > & ResultsSoFar_) [virtual]
Add in a large set of results to what we already have
Parameters:
Number_ The number of results to add in
ResultsSoFar_ 2D vector of results size (1,2) , with two elements, [0] = mean, [1] = standard deviation
Implements StatGathering::StatisticsMC .
Definition at line 24 of file statisticsmc.cpp.
References PathsDone, RunningSum, and RunningSum2.
Referenced by SetResultsSoFar().
26 {
27   PathsDone += Number_;
28 
29   // ResultsSoFar_ is passed in as two elements: the mean and the standard deviation
30   double mean, sd, num;
31   num = static_cast<double>(Number_);
32   mean = ResultsSoFar_[0][0];
33   sd = ResultsSoFar_[0][1];
34 
35   // ... but we store internally as total total of squares
36   // now convert from mean, sd to total, total of squres
37   RunningSum += mean * num;
38   RunningSum2 += (sd*sd*num + mean*mean) * num;
39 }
void StatGathering::StatisticsMean::Reset () [virtual]
Reset all internal values to zero.
Implements StatGathering::StatisticsMC .
Definition at line 41 of file statisticsmc.cpp.
References PathsDone, RunningSum, and RunningSum2.
Referenced by SetResultsSoFar().
42 {
43   PathsDone = 0;
44   RunningSum = 0.;
45   RunningSum2 = 0.;
46 }
void StatGathering::StatisticsMean::SetResultsSoFar (long Number_, std::vector< std::vector< double > > & ResultsSoFar_) [virtual]
Set to a specific set of results.
Implements StatGathering::StatisticsMC .
Definition at line 48 of file statisticsmc.cpp.
References AddOneSetOfResults(), and Reset().
Referenced by StatGathering::operator>>().
50 {
51   Reset();
52   AddOneSetOfResults( Number_, ResultsSoFar_ );
53 }
std::vector< std::vector< double > > StatGathering::StatisticsMean::GetResultsSoFar () const [virtual]
Get the results so far 2D vector of results: in this case, dimensions (1,2) The two elements are: mean, standard deviation
Returns: Return by value, a 2D vector of dimension (1,2) giving mean, standard deviation
Implements StatGathering::StatisticsMC .
Definition at line 55 of file statisticsmc.cpp.
References PathsDone, RunningSum, and RunningSum2.
Referenced by StatGathering::operator<<().
56 {
57   // Construct our 2D vector
58   std::vector<std::vector<double> > Results(1);
59   Results[0].resize(2);
60 
61   // Calculate the mean and standard deviation
62   Results[0][0] = RunningSum / PathsDone;
63   Results[0][1] = sqrt( (RunningSum2 / PathsDone - Results[0][0]*Results[0][0]) / PathsDone );
64 
65   return Results;
66 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const StatisticsMean & stats) [friend]
friend to << so that we can overload the << operator to output a ConvergenceTable object
Definition at line 73 of file statisticsmc.cpp.
74 {
75   std::vector<std::vector<double> > theResults = stats.GetResultsSoFar();
76   double mean = theResults[0][0];
77   double sd = theResults[0][1];
78 
79   out << mean << " " << sd << " " << stats.PathsDone;
80 
81   return ( out );
82 }
std::istream& operator>> (std::istream & in, StatisticsMean & stats) [friend]
Definition at line 84 of file statisticsmc.cpp.
85 {
86   std::vector<std::vector<double> > theResults( 1 );
87   theResults[0].resize(2);
88   unsigned long pathsDone;
89 
90   double mean;
91   double sd;
92 
93   in >> mean >> sd >> pathsDone;
94   theResults[0][0] = mean;
95   theResults[0][1] = sd;
96 
97   stats.SetResultsSoFar( pathsDone, theResults );
98  
99   return ( in );
100 }
Member Data Documentation
double StatGathering::StatisticsMean::RunningSum [private]
The sum of all the input results.
Definition at line 99 of file statisticsmc.h.
Referenced by AddOneResult(), AddOneSetOfResults(), GetResultsSoFar(), and Reset().
double StatGathering::StatisticsMean::RunningSum2 [private]
The sum of all the squares of input results.
Definition at line 101 of file statisticsmc.h.
Referenced by AddOneResult(), AddOneSetOfResults(), GetResultsSoFar(), and Reset().
unsigned long StatGathering::StatisticsMean::PathsDone [private]
The total number of points input.
Definition at line 103 of file statisticsmc.h.
Referenced by AddOneResult(), AddOneSetOfResults(), GetResultsSoFar(), StatGathering::operator<<(), and Reset().
The documentation for this class was generated from the following files:
Gyulassy/opacity3/src/store2d/statisticsmc.h
Gyulassy/opacity3/src/store2d/statisticsmc.cpp