RadCalcerWrapper< numOfRandoms > Class Template Reference
#include <radcalcerwrapper.h>
Public Member Functions
RadCalcerWrapper ()
~RadCalcerWrapper ()
void SetParameters (Parameters &inParams)
void SetCoord (long dimension, double value)
void SetRandoms (SwArrays::MyArray &randomNumbers)
void GetAnswer (SwArrays::MyArray &answers)
Private Attributes
RadCalcer * radcalc
Detailed Description
template<std::size_t numOfRandoms> class RadCalcerWrapper< numOfRandoms >
Author:
Definition at line 25 of file radcalcerwrapper.h.
Constructor & Destructor Documentation
template<std::size_t numOfRandoms> RadCalcerWrapper< numOfRandoms >::RadCalcerWrapper () [inline]
Definition at line 31 of file radcalcerwrapper.h.
32   {
33 
34   };
template<std::size_t numOfRandoms> RadCalcerWrapper< numOfRandoms >::~RadCalcerWrapper () [inline]
Definition at line 36 of file radcalcerwrapper.h.
References RadCalcerWrapper< numOfRandoms >::radcalc.
37   {
38     delete radcalc;
39   };
Member Function Documentation
template<std::size_t numOfRandoms> void RadCalcerWrapper< numOfRandoms >::SetParameters (Parameters & inParams) [inline]
Definition at line 41 of file radcalcerwrapper.h.
References RadCalcerWrapper< numOfRandoms >::radcalc.
42   {
43     long opacity = numOfRandoms / 3;
44     radcalc = new RadCalcer( inParams, opacity, true );
45   };
template<std::size_t numOfRandoms> void RadCalcerWrapper< numOfRandoms >::SetCoord (long dimension, double value) [inline]
Definition at line 47 of file radcalcerwrapper.h.
References RadCalcerWrapper< numOfRandoms >::radcalc, RadCalcer::SetKonly(), and RadCalcer::SetXonly().
48   {
49     // Dimension 1 = k
50     // Dimension 2 = x
51 
52     switch (dimension)
53     {
54       case 1:
55         radcalc->SetKonly( value );
56         break;
57 
58       case 2:
59         radcalc->SetXonly( value );
60         break;
61 
62       default:
63         break;
64     }
65   };
template<std::size_t numOfRandoms> void RadCalcerWrapper< numOfRandoms >::SetRandoms (SwArrays::MyArray & randomNumbers) [inline]
Definition at line 67 of file radcalcerwrapper.h.
References RadCalcer::DistributeRandoms(), and RadCalcerWrapper< numOfRandoms >::radcalc.
68   {
69     radcalc->DistributeRandoms( randomNumbers );
70   };
template<std::size_t numOfRandoms> void RadCalcerWrapper< numOfRandoms >::GetAnswer (SwArrays::MyArray & answers) [inline]
Definition at line 72 of file radcalcerwrapper.h.
References RadCalcer::GetdNdk2dx(), and RadCalcerWrapper< numOfRandoms >::radcalc.
73   {
74     radcalc->GetdNdk2dx( answers );
75   };
Member Data Documentation
template<std::size_t numOfRandoms> RadCalcer* RadCalcerWrapper< numOfRandoms >::radcalc [private]
Definition at line 28 of file radcalcerwrapper.h.
Referenced by RadCalcerWrapper< numOfRandoms >::GetAnswer(), RadCalcerWrapper< numOfRandoms >::SetCoord(), RadCalcerWrapper< numOfRandoms >::SetParameters(), RadCalcerWrapper< numOfRandoms >::SetRandoms(), and RadCalcerWrapper< numOfRandoms >::~RadCalcerWrapper().
The documentation for this class was generated from the following file:
Gyulassy/opacity3/src/glv1/radcalcerwrapper.h