SwRandoms::RandSobol Class Reference
#include <RandSobol.h>
Public Member Functions
RandSobol (unsigned long Dimensionality, unsigned long Seed=1)
virtual RandomBase2 * clone () const
virtual void GetUniforms (SwArrays::MyArray &variates)
virtual void Skip (unsigned long numberOfPaths)
virtual void SetSeed (unsigned long Seed)
virtual void Reset ()
Private Attributes
long long int InitialSeed
long long int RunningSeed
Detailed Description
Definition at line 9 of file RandSobol.h.
Constructor & Destructor Documentation
SwRandoms::RandSobol::RandSobol (unsigned long Dimensionality, unsigned long Seed = 1)
Definition at line 9 of file RandSobol.cpp.
Referenced by clone().
10   : RandomBase2(Dimensionality), InitialSeed( Seed )
11 {
12 
13 }
Member Function Documentation
RandomBase2 * SwRandoms::RandSobol::clone () const [virtual]
Implements SwRandoms::RandomBase2 .
Definition at line 15 of file RandSobol.cpp.
References RandSobol().
16 {
17   return new RandSobol( *this );
18 }
void SwRandoms::RandSobol::GetUniforms (SwArrays::MyArray & variates) [virtual]
Implements SwRandoms::RandomBase2 .
Definition at line 20 of file RandSobol.cpp.
References SwRandoms::RandomBase2::GetDimensionality(), Sobol::i8_sobol(), and RunningSeed.
Referenced by Skip().
21 {
22   unsigned long dim = GetDimensionality();
23   double* sobols = new double[dim];
24   
25   // Produces a vector of quasirandom numbers
26   // Updates RunningSeed
27   Sobol::i8_sobol( dim, &RunningSeed, sobols );
28 
29   // Move our array of floats into the vector
30   for (unsigned long j=0; j<dim; j++)
31     variates[j] = sobols[j];
32 
33   delete [] sobols;
34 }
void SwRandoms::RandSobol::Skip (unsigned long numberOfPaths) [virtual]
Implements SwRandoms::RandomBase2 .
Definition at line 36 of file RandSobol.cpp.
References SwRandoms::RandomBase2::GetDimensionality(), and GetUniforms().
37 {
38   SwArrays::MyArray tmp( GetDimensionality() );
39   for (unsigned long j=0; j<numberOfPaths; j++)
40     GetUniforms(tmp);
41 }
void SwRandoms::RandSobol::SetSeed (unsigned long Seed) [virtual]
Implements SwRandoms::RandomBase2 .
Definition at line 43 of file RandSobol.cpp.
References InitialSeed, and RunningSeed.
44 {
45   //InitialSeed = Seed;
46   // Sobol sequence should start from 0
47   InitialSeed = 0;
48   RunningSeed = InitialSeed;
49   srand48( Seed );
50 }
void SwRandoms::RandSobol::Reset () [virtual]
Implements SwRandoms::RandomBase2 .
Definition at line 52 of file RandSobol.cpp.
References InitialSeed.
53 {
54   srand48( InitialSeed );
55 }
Member Data Documentation
long long int SwRandoms::RandSobol::InitialSeed [private]
Definition at line 21 of file RandSobol.h.
Referenced by Reset(), and SetSeed().
long long int SwRandoms::RandSobol::RunningSeed [private]
Definition at line 22 of file RandSobol.h.
Referenced by GetUniforms(), and SetSeed().
The documentation for this class was generated from the following files:
Gyulassy/opacity3/src/randoms/RandSobol.h
Gyulassy/opacity3/src/randoms/RandSobol.cpp