QperpCalculator1< n > Class Template Reference
#include <qperpcalculator1.h>
Public Member Functions
QperpCalculator1 ()
void SetK (double k)
void SetQsThetas (boost::array< double, n > &Qs, boost::array< double, n > &Thetas)
double GetSumQskk (long m, long zeroes) const
double GetSumQs1k (long m, long zeroes) const
Private Attributes
QperpCalculator qperps
Detailed Description
template<std::size_t n> class QperpCalculator1< n >
Author: Simon Wicks <simonw@phys.columbia.edu> A wrapper around the QperpCalculator from the old version, version1, to use in the newer GlvRadiative3 template calcaluation The interface necessary for GlvRadiative3 is converted into the relevant calls for the old code. In this way, the old, tested qperpcalculator can be used in the newer code, to compare to results for any newer versions.
Definition at line 26 of file qperpcalculator1.h.
Constructor & Destructor Documentation
template<std::size_t n> QperpCalculator1< n >::QperpCalculator1 () [inline]
Definition at line 31 of file qperpcalculator1.h.
31                      : qperps( n, true )
32   {
33 
34   };
Member Function Documentation
template<std::size_t n> void QperpCalculator1< n >::SetK (double k) [inline]
Definition at line 36 of file qperpcalculator1.h.
References QperpCalculator1< n >::qperps, and QperpCalculator::SetK().
Referenced by main().
37   {
38     qperps.SetK( k );
39   };
template<std::size_t n> void QperpCalculator1< n >::SetQsThetas (boost::array< double, n > & Qs, boost::array< double, n > & Thetas) [inline]
Definition at line 41 of file qperpcalculator1.h.
References QperpCalculator1< n >::qperps, and QperpCalculator::SetQperps().
Referenced by main().
43   {
44     SwArrays::MyArray qs1(n), thetas1(n);
45     for ( std::size_t i=0; i<n; ++i )
46     {
47       qs1[i] = Qs[i]; thetas1[i] = Thetas[i];
48     }
49     qperps.SetQperps( qs1, thetas1 );
50   };
template<std::size_t n> double QperpCalculator1< n >::GetSumQskk (long m, long zeroes) const [inline]
Definition at line 52 of file qperpcalculator1.h.
References QperpCalculator::GetSumQiQj(), and QperpCalculator1< n >::qperps.
Referenced by main().
53   {
54     return qperps.GetSumQiQj( m, m, zeroes );
55   };
template<std::size_t n> double QperpCalculator1< n >::GetSumQs1k (long m, long zeroes) const [inline]
Definition at line 57 of file qperpcalculator1.h.
References QperpCalculator::GetSumQiQj(), and QperpCalculator1< n >::qperps.
Referenced by main().
58   {
59     return qperps.GetSumQiQj( 1, m, zeroes );
60   };
Member Data Documentation
template<std::size_t n> QperpCalculator QperpCalculator1< n >::qperps [private]
Definition at line 29 of file qperpcalculator1.h.
Referenced by QperpCalculator1< n >::GetSumQs1k(), QperpCalculator1< n >::GetSumQskk(), QperpCalculator1< n >::SetK(), and QperpCalculator1< n >::SetQsThetas().
The documentation for this class was generated from the following file:
Gyulassy/opacity3/src/glv3/qperpcalculator1.h