Store2D Class Reference
#include <store.h>
Public Member Functions
Store2D ()
Store2D (long SizeDim1_, long SizeDim2_, long SizePerPoint_)
Constructor, supplying the dimensions of the store grid.
void SetParameters (Parameters &inParams)
int ReadFromFile (std::string FileName_)
void WriteToFile (std::string FileName_, bool append)
Write everything to file.
int SetSize (long Size1_, long Size2_, long SizePerPoint_)
Resize the store.
void SetLimitsDim1 (double MinDim1_, double MaxDim1_)
Set the limits in dimension 1.
void SetLimitsDim2 (double MinDim2_, double MaxDim2_)
Set the limits in dimension 2.
void AddPoint (long IndexDim1_, long IndexDim2_, MyArray &Values_)
double GetCoordDim1 (long IndexDim1_) const
Get the coordinate in dimension 1 corresponding to the given index.
double GetCoordDim2 (long IndexDim2_) const
Get the coordinate in dimension 2 corresponding to the given index.
void GetCoords (long IndexDim1_, long IndexDim2_, double &ValDim1, double &ValDim2) const
Get the 2D coordinates corresponding to the given indices.
long GetLengthDim1 () const
long GetLengthDim2 () const
long GetNumIterations (long opac, long kth, long xth)
Private Member Functions
long GetIndex (long IndexDim1, long IndexDim2) const
Helper function to turn (IndexDim1,IndexDim2) into a 1D index.
Private Attributes
long SizeDim1
The number of points in dimension 1, excluding the starting point.
double MinDim1
The Starting point of dimension 1.
double MaxDim1
The finishing point of dimension 1.
double StepDim1
long SizeDim2
The number of points in dimension 2, excluding the starting point.
double MinDim2
The Starting point of dimension 2.
double MaxDim2
The finishing point of dimension 2.
double StepDim2
long SizePerPoint
The size of the array of information for each point.
boost::multi_array< Wrapper< StatisticsMC >, 2 > stats
Friends
std::ostream & operator<< (std::ostream &out, const Store2D &store)
friend to << so that we can overload it to output a Store2D object
std::istream & operator>> (std::istream &in, Store2D &store)
Detailed Description
A two dimensional store of results, with an arbitrary length array of StatisticsMC derived objects for each point. Mechanisms for storage to file and resumption from file are provided. File format: section begins with '# Begin Store2D data' and ends with '# End Store2D data'. In between this are all the data point, the number corresponding to the Parameters section in the same file (which has already been read). Blank lines and lines beginning with # are ignored.
Dimension1 = k; Dimension2 = x;
TODO: generalise this class for an arbitrary dimension result.
Definition at line 29 of file store.h.
Constructor & Destructor Documentation
Store2D::Store2D ()
Definition at line 13 of file store.cpp.
14 {
15 
16 }
Store2D::Store2D (long SizeDim1_, long SizeDim2_, long SizePerPoint_)
Constructor, supplying the dimensions of the store grid.
Definition at line 18 of file store.cpp.
References SetSize().
19 {
20   SetSize( SizeDim1_, SizeDim2_, SizePerPoint_ );
21 }
Member Function Documentation
long Store2D::GetIndex (long IndexDim1, long IndexDim2) const [inline, private]
Helper function to turn (IndexDim1,IndexDim2) into a 1D index.
Definition at line 113 of file store.h.
References SizeDim2.
Referenced by AddPoint(), GetNumIterations(), operator<<(), and operator>>().
114 {
115   return ( IndexDim1_*(SizeDim2+1) + IndexDim2_ );
116 }
void Store2D::SetParameters (Parameters & inParams)
Definition at line 23 of file store.cpp.
References Parameters::GetParametersDouble(), SetLimitsDim1(), SetLimitsDim2(), and SetSize().
24 {
25   std::vector<double> ReturnedParamsDouble1, ReturnedParamsDouble2;
26   std::list<std::string> ReturnedParamsString;  
27 
28   // First, get the details from the parameters object
29   double min1, max1, min2, max2;
30   long size1, size2;
31   ReturnedParamsDouble1 = MyParameters.GetParametersDouble( "@storedim1" );
32   if ( ReturnedParamsDouble1.size() < 3 )
33     std::cerr << "Error with @storedim1" << std::endl;
34   ReturnedParamsDouble2 = MyParameters.GetParametersDouble( "@storedim2" );
35   if ( ReturnedParamsDouble2.size() < 3 )
36     std::cerr << "Error with @storedim2" << std::endl;
37   size1 = long(ReturnedParamsDouble1.at(2)+0.5);
38   size2 = long(ReturnedParamsDouble2[2]+0.5);
39   min1 = ReturnedParamsDouble1[0];
40   min2 = ReturnedParamsDouble2[0];
41   max1 = ReturnedParamsDouble1[1];
42   max2 = ReturnedParamsDouble2[1];
43 
44   SetSize( size1, size2, 1 );
45   SetLimitsDim1( ReturnedParamsDouble1[0], ReturnedParamsDouble1[1] );
46   SetLimitsDim2( ReturnedParamsDouble2[0], ReturnedParamsDouble2[1] );
47 }
int Store2D::ReadFromFile (std::string FileName_)
Get all the store data from a file, and resume from that point
Returns: Integer error code: either 0, or negative number indicating error
Definition at line 101 of file store.cpp.
102 {
103   // Reading in a file, and putting it in the store
104   // The code here is very similar to that in the parameters.cpp for reading
105   // in the parameters from a file
106 
107   // First, we open the file and check that it exists
108   std::ifstream FileIn;
109   FileIn.open( FileName_.c_str(), std::ios::in );
110   if ( FileIn.fail() )
111   {
112     std::cerr << "Store2D, unable to open file " << FileName_;
113     std::cerr << " for reading." << std::endl;
114     return -20;
115   }
116 
117   // Each line, we'll read into LineReadIn
118   // Each line of settings will be counted in NumberOfLines
119   std::string LineReadIn;
120 
121   // Ok, we have an open file, we want to find the data section
122   // The string that identifies the beginning of the settings section
123   std::string BeginString = "# Begin Store2D data";
124   // The string that identifies the end of the settings section
125   std::string EndString = "# End Store2D data";
126 
127   // Indicator whether we have found the settings section yet
128   bool FoundStart;
129   // Run through the file until we find the settings section
130   do
131   {
132     if ( FileIn.eof() )
133     {
134       std::cerr << "Store2D, reached end of file at line before "; 
135       std::cerr << "finding data section" << std::endl;
136       return -21;
137     }
138     getline( FileIn, LineReadIn );
139     boost::trim( LineReadIn );
140     if ( LineReadIn == BeginString )
141       FoundStart = true;
142   }
143   while ( !FoundStart );
144 
145   // Now, pass off the logic to the >> operator
146   FileIn >> *this;
147 
148   // Now we're done, we close the file
149   FileIn.close();
150   
151   // Everything has worked fine. 
152   // Return a success code
153   return 0;
154 }
void Store2D::WriteToFile (std::string FileName_, bool append)
Write everything to file.
Definition at line 156 of file store.cpp.
157 {
158   // First, open the file
159   std::ofstream FileOut;
160   if ( append )
161   {
162     FileOut.open( FileName_.c_str(), std::ios::app );
163   }
164   else
165   {
166     FileOut.open( FileName_.c_str(), std::ios::trunc );
167   }
168   
169   // Check for errors
170   if ( FileOut.fail() )
171   {
172     std::cerr << "Store2D, unable to open file " << FileName_;
173     std::cerr << " for writing." << std::endl;
174   }
175 
176   FileOut << "# Begin Store2D data" << std::endl;
177   FileOut << *this;
178   FileOut << "# End Store2D data" << std::endl;
179   FileOut.close();
180 }
int Store2D::SetSize (long Size1_, long Size2_, long SizePerPoint_)
Resize the store.
Definition at line 49 of file store.cpp.
References SizeDim1, SizeDim2, SizePerPoint, and stats.
Referenced by SetParameters(), and Store2D().
50 {
51   SizeDim1 = Size1_;
52   SizeDim2 = Size2_;
53   SizePerPoint = SizePerPoint_;
54 
55   stats.resize( boost::extents[ (SizeDim1+1)*(SizeDim2+1) ][SizePerPoint] );
56 
57   // We want to set up all the StatisticsMC as pointers to
58   // ConvergenceTable objects containing StatisticsMean objects
59   StatisticsMean gatherer;
60   ConvergenceTable tab(gatherer);
61 
62   for (long i=0; i!=(SizeDim1+1)*(SizeDim2+1); ++i)
63     for (long opac=0; opac!=SizePerPoint; ++opac)
64       stats[i][opac] = tab;
65 
66   return 0;
67 }
void Store2D::SetLimitsDim1 (double MinDim1_, double MaxDim1_)
Set the limits in dimension 1.
Definition at line 69 of file store.cpp.
References MaxDim1, MinDim1, SizeDim1, and StepDim1.
Referenced by SetParameters().
70 {
71   MinDim1 = MinDim1_;
72   MaxDim1 = MaxDim1_;
73   // For convenience, we calculate the fixed step size and store it
74   StepDim1 = (MaxDim1-MinDim1)/double(SizeDim1);
75 }
void Store2D::SetLimitsDim2 (double MinDim2_, double MaxDim2_)
Set the limits in dimension 2.
Definition at line 77 of file store.cpp.
References MaxDim2, MinDim2, SizeDim2, and StepDim2.
Referenced by SetParameters().
78 {
79   MinDim2 = MinDim2_;
80   MaxDim2 = MaxDim2_;
81   // For convenience, we calculate the fixed step size and store it
82   StepDim2 = (MaxDim2_-MinDim2_)/static_cast<double>(SizeDim2);
83 }
void Store2D::AddPoint (long IndexDim1_, long IndexDim2_, MyArray & Values_)
Add a new Monte Carlo point to our results - at (IndexDim1_,IndexDim2_) with an array of values given by Values_
Definition at line 85 of file store.cpp.
References GetIndex(), SizePerPoint, and stats.
86 {
87   for (long i=0; i<SizePerPoint; ++i)
88     stats[GetIndex( IndexDim1_, IndexDim2_ )][i]->AddOneResult( Values_[i] );
89 }
double Store2D::GetCoordDim1 (long IndexDim1_) const [inline]
Get the coordinate in dimension 1 corresponding to the given index.
Definition at line 118 of file store.h.
References MinDim1, and StepDim1.
Referenced by GetCoords(), and operator<<().
119 {
120   return ( MinDim1 + static_cast<double>(IndexDim1_) * StepDim1 );
121 }
double Store2D::GetCoordDim2 (long IndexDim2_) const [inline]
Get the coordinate in dimension 2 corresponding to the given index.
Definition at line 123 of file store.h.
References MinDim2, and StepDim2.
Referenced by GetCoords(), and operator<<().
124 {
125   return ( MinDim2 + static_cast<double>(IndexDim2_) * StepDim2 );
126 }
void Store2D::GetCoords (long IndexDim1_, long IndexDim2_, double & ValDim1, double & ValDim2) const [inline]
Get the 2D coordinates corresponding to the given indices.
Definition at line 128 of file store.h.
References GetCoordDim1(), and GetCoordDim2().
130 {
131   ValDim1 = GetCoordDim1( IndexDim1_ );
132   ValDim2 = GetCoordDim2( IndexDim2_ );
133 }
long Store2D::GetLengthDim1 () const [inline]
Definition at line 135 of file store.h.
References SizeDim1.
136 {
137   return SizeDim1;
138 }
long Store2D::GetLengthDim2 () const [inline]
Definition at line 140 of file store.h.
References SizeDim2.
141 {
142   return SizeDim2;
143 }
long Store2D::GetNumIterations (long opac, long kth, long xth)
Definition at line 91 of file store.cpp.
References GetIndex(), and stats.
92 {
93   std::vector<std::vector<double> > res = 
94         stats[GetIndex( kth, xth )][opac]->GetResultsSoFar();
95   
96   std::vector<std::vector<double> >::iterator it;
97   it = res.end(); --it;
98   return static_cast<long>( it->at(2) );
99 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const Store2D & store) [friend]
friend to << so that we can overload it to output a Store2D object
Definition at line 182 of file store.cpp.
183 {
184   // Assume that all the preliminaries have been written
185   // All we have to do here is write the data to file / stream
186 
187   // Format: dim1 dim2 results....
188   // Incrementing dim1, then dim2
189   
190   // If there are multiple data sets per point, output one whole set then the next
191   // Hence, outer iteration is over data sets per point
192   for (long i=0; i<store.SizePerPoint; ++i)
193   {
194     // Inner iteration over all points
195     for (long dim2=0; dim2<store.SizeDim2; ++dim2)
196     {
197       for (long dim1=0; dim1<store.SizeDim1; ++dim1)
198       {
199         // First, write the k, x coords to file
200         // (for ease of reading either manually or by eg Mathematica)
201         out << store.GetCoordDim1( dim1 ) << " " << store.GetCoordDim2( dim2 ) << " ";
202         // Pass off the logic of writing to the ConvergenceTable object
203         const ConvergenceTable* conTab = static_cast<const ConvergenceTable*>
204                  ( store.stats[ store.GetIndex( dim1, dim2 ) ][i].GetConstPointer() );
205         out << *conTab;
206         out << std::endl;
207       }
208     }
209   }
210 
211   // We're done, all overloading of << has to return the supplied ostream
212   return ( out );
213 }
std::istream& operator>> (std::istream & in, Store2D & store) [friend]
Definition at line 215 of file store.cpp.
216 {
217   // TODO: improve this to handle possible alterations to the file
218   // eg blank lines, comment lines etc, handle errors and bad files properly
219 
220   double coordDim1, coordDim2;
221   // Hence, outer iteration is over data sets per point
222   for (long i=0; i<store.SizePerPoint; ++i)
223   {
224     // Inner iteration over all points
225     for (long dim2=0; dim2<store.SizeDim2; ++dim2)
226     {
227       for (long dim1=0; dim1<store.SizeDim1; ++dim1)
228       {
229         // First, we have the coords in dim1 and dim2
230         in >> coordDim1 >> coordDim2;
231         // Pass off the logic of reading to the ConvergenceTable object
232         ConvergenceTable* conTab = static_cast<ConvergenceTable*>
233                  ( store.stats[ store.GetIndex( dim1, dim2 ) ][i].GetPointer() );
234         in >> *conTab;
235       }
236     }
237   }
238 
239   return ( in );
240 }
Member Data Documentation
long Store2D::SizeDim1 [private]
The number of points in dimension 1, excluding the starting point.
Definition at line 37 of file store.h.
Referenced by GetLengthDim1(), operator<<(), operator>>(), SetLimitsDim1(), and SetSize().
double Store2D::MinDim1 [private]
The Starting point of dimension 1.
Definition at line 39 of file store.h.
Referenced by GetCoordDim1(), and SetLimitsDim1().
double Store2D::MaxDim1 [private]
The finishing point of dimension 1.
Definition at line 41 of file store.h.
Referenced by SetLimitsDim1().
double Store2D::StepDim1 [private]
The step size (derived from Size,Min,Max) in dimension 1, MaxDim1 = MinDim1 + StepDim1 * SizeDim1
Definition at line 45 of file store.h.
Referenced by GetCoordDim1(), and SetLimitsDim1().
long Store2D::SizeDim2 [private]
The number of points in dimension 2, excluding the starting point.
Definition at line 48 of file store.h.
Referenced by GetIndex(), GetLengthDim2(), operator<<(), operator>>(), SetLimitsDim2(), and SetSize().
double Store2D::MinDim2 [private]
The Starting point of dimension 2.
Definition at line 50 of file store.h.
Referenced by GetCoordDim2(), and SetLimitsDim2().
double Store2D::MaxDim2 [private]
The finishing point of dimension 2.
Definition at line 52 of file store.h.
Referenced by SetLimitsDim2().
double Store2D::StepDim2 [private]
The step size (derived from Size,Min,Max) in dimension 2, MaxDim2 = MinDim2 + StepDim2 * SizeDim2
Definition at line 56 of file store.h.
Referenced by GetCoordDim2(), and SetLimitsDim2().
long Store2D::SizePerPoint [private]
The size of the array of information for each point.
Definition at line 59 of file store.h.
Referenced by AddPoint(), operator<<(), operator>>(), and SetSize().
boost::multi_array<Wrapper<StatisticsMC>, 2 > Store2D::stats [private]
The array of pointers (wrappers) to Statistics gatherers The first dimension is the 2D store combined into 1 dimension The second dimension corresponds to a size of SizePerPoint
Definition at line 64 of file store.h.
Referenced by AddPoint(), GetNumIterations(), operator<<(), operator>>(), and SetSize().
The documentation for this class was generated from the following files:
Gyulassy/opacity3/src/store2d/store.h
Gyulassy/opacity3/src/store2d/store.cpp