RadCalcer Class Reference
#include <radcalcer.h>
Public Member Functions
RadCalcer (Parameters &params_, long opacity_, bool correlated_)
~RadCalcer ()
void DistributeRandoms (MyArray &Randoms)
void SetXonly (double x)
void SetKonly (double k)
double Getkmax () const
void GetdNdk2dx (MyArray &results)
Private Member Functions
double _interference (unsigned long m) const
double _interferenceExp (unsigned long m) const
double _cdotb (unsigned long m) const
Private Attributes
ZposGenerator zDist
QperpGenerator qperps
const long n
double _x
double _overx
double _k
double _en
double _mass
double _cr
double _temp
double _mg
double _lambda
double _length
double _alphas
unsigned long _switchkmax
double _dglv
double _frac
bool _correlated
bool _diffexclude
Detailed Description
Definition at line 11 of file radcalcer.h.
Constructor & Destructor Documentation
RadCalcer::RadCalcer (Parameters & params_, long opacity_, bool correlated_)
Definition at line 11 of file radcalcer.cpp.
References _alphas, _correlated, _cr, _diffexclude, _en, _length, _mass, _mg, _switchkmax, Parameters::GetParametersDouble(), Parameters::GetParametersLong(), and Parameters::GetParametersString().
12   : zDist( params_, opacity_ ), qperps( opacity_, correlated_ ), n( opacity_ )
13 {
14   std::vector<double> ReturnedParamsDouble;
15   std::vector<long> ReturnedParamsLong;
16   std::list<std::string> ReturnedParamsString;
17   std::list<std::string>::iterator it;
18 
19   // First, we get the parameters of the medium
20   // This is: 1st = mu, 2nd = temperature, 3rd = gluon mass, 4th = gluon mean free path
21   // Here, we only need the gluon mass
22   // the zDist will need the others
23   ReturnedParamsDouble = params_.GetParametersDouble( "@mediumParams" );
24   _mg = ReturnedParamsDouble[2];
25 
26   // Next, get the jet flavour
27   ReturnedParamsString = params_.GetParametersString( "@jetFlavour" );
28   std::string jetFlavour = ReturnedParamsString.front();
29   if ( jetFlavour == "Gluon" )
30   {
31     _cr = 3.; _mass = _mg;
32   }
33   else if ( jetFlavour == "Light" )
34   {
35     _cr = 4./3.; _mass = _mg / sqrt(2);
36   }
37   else if ( jetFlavour == "Charm" )
38   {
39     _cr = 4./3.; _mass = 1.2;
40   }
41   else if ( jetFlavour == "Bottom" )
42   {
43     _cr = 4./3.; _mass = 4.75;
44   }
45   else
46   {
47     std::cerr << "@jetFlavour not understood" << std::endl;
48     exit(0);
49   }
50 
51   // Now, check whether also specifying a jet mass
52   ReturnedParamsDouble = params_.GetParametersDouble( "@jetMassDirect" );
53   if ( ReturnedParamsDouble.size() > 0 )
54     _mass = ReturnedParamsDouble[0];
55   
56   // Now, the momentum, to give the jet energy
57   ReturnedParamsDouble = params_.GetParametersDouble( "@jetMomentum" );
58   double jetMomentum = ReturnedParamsDouble[0];
59   // Now calculate and set energy, and mass
60   _en = sqrt( _mass*_mass + jetMomentum*jetMomentum );
61 
62   // The jet path length in the medium
63   ReturnedParamsDouble = params_.GetParametersDouble( "@pathLength" );
64   _length = ReturnedParamsDouble[0];
65 
66   // The setting on the k max
67   ReturnedParamsLong = params_.GetParametersLong( "@limitSet" );
68   _switchkmax = ReturnedParamsLong[0];
69 
70   // The strong coupling, alpha_s
71   ReturnedParamsString = params_.GetParametersString( "@alpha" );
72   it = ReturnedParamsString.begin();
73   if ( *it == "fixed" )
74   {
75     ++it;
76     _alphas = boost::lexical_cast<double>( *it );
77   }
78   else
79   {
80     std::cerr << "Radcalcer, @alpha not understood";
81     std::cerr << std::endl;
82     exit(0);
83   }
84 
85   ReturnedParamsString = params_.GetParametersString( "@incClassicalDiffusion" );
86   if ( ReturnedParamsString.front() == "yes" )
87     _diffexclude = false;
88   else if ( ReturnedParamsString.front() == "no" )
89     _diffexclude = true;
90   else
91   {
92     std::cerr << "Radcalcer, @incClassicalDiffusion not understood as yes or no";
93     std::cerr << std::endl;
94     exit(0);
95   }
96 
97 
98   _correlated = correlated_;
99 }
RadCalcer::~RadCalcer ()
Definition at line 101 of file radcalcer.cpp.
102 {
103 
104 }
Member Function Documentation
double RadCalcer::_interference (unsigned long m) const [private]
Definition at line 148 of file radcalcer.cpp.
References _dglv, _frac, ZposGenerator::GetDeltaZi(), QperpGenerator::GetSumQiQj(), qperps, and zDist.
149 {
150   double term1 = 0.;
151   double term2 = 0.;
152 
153   for (unsigned long k=2; k<=m; k++)
154   {
155     term1 += (qperps.GetSumQiQj( k, k )+_dglv) * zDist.GetDeltaZi( k );
156   }
157   term2 = term1 + (qperps.GetSumQiQj( 1, 1 )+_dglv) * zDist.GetDeltaZi( 1 );
158 
159   double tmp = cos(term1*_frac) - cos(term2*_frac);
160 
161   return tmp;
162 }
double RadCalcer::_interferenceExp (unsigned long m) const [private]
Definition at line 164 of file radcalcer.cpp.
References _dglv, _frac, _length, QperpGenerator::GetSumQiQj(), n, and qperps.
Referenced by GetdNdk2dx().
165 {
166   double result1, result2;
167   double omknLen;
168 
169   //double realpart = 1.; double imagpart = 0.;
170 
171   /*for ( unsigned long k=2; k<=m; ++k )
172   {
173     omknLen = (qperps.GetSumQiQj( k, k )+_dglv)*_frac * _length / static_cast<double>(n+1);
174     realpart = realpart*1. - imagpart*omknLen;
175     imagpart = imagpart*1. + realpart*omknLen;
176   }
177 
178   result1 = realpart / (realpart*realpart + imagpart*imagpart);
179 
180   omknLen = (qperps.GetSumQiQj( 1, 1 )+_dglv)*_frac * _length / static_cast<double>(n+1);
181   realpart = realpart*1. - imagpart*omknLen;
182   imagpart = imagpart*1. + realpart*omknLen;
183 
184   result2 = realpart / (realpart*realpart + imagpart*imagpart);*/
185 
186   std::complex<double> den = std::complex<double>(1.,0.);
187   double qpkk;
188   for ( unsigned long k=2; k<=m; ++k ) 
189   {
190     qpkk = qperps.GetSumQiQj( k, k );
191     omknLen = (qpkk+_dglv)*_frac * _length / static_cast<double>(n+1);
192     den *= std::complex<double>( 1., omknLen );
193   }
194   
195   result1 = den.real() / ( pow(den.real(),2) + pow(den.imag(),2) );
196   
197   qpkk = qperps.GetSumQiQj( 1, 1 );
198   omknLen = (qpkk+_dglv)*_frac * _length / static_cast<double>(n+1);
199   den *= std::complex<double>( 1., omknLen );
200   
201   result2 = den.real() / ( pow(den.real(),2) + pow(den.imag(),2) );
202   
203   return ( result1 - result2 );
204 }
double RadCalcer::_cdotb (unsigned long m) const [private]
Definition at line 206 of file radcalcer.cpp.
References _dglv, QperpGenerator::GetSumQiQj(), and qperps.
Referenced by GetdNdk2dx().
207 {
208   double qs11 = qperps.GetSumQiQj( 1, 1 );
209   double qsmp1mp1 = qperps.GetSumQiQj( m+1, m+1 );
210   double qsmm = qperps.GetSumQiQj( m, m );
211 
212   double qs1m = qperps.GetSumQiQj( 1, m );
213   double qs1mp1 = qperps.GetSumQiQj( 1, m+1 );
214 
215   double tmp = ( qs1mp1/(qsmp1mp1+_dglv) - qs1m/(qsmm+_dglv) ) / (qs11+_dglv);
216   return tmp;
217 }
void RadCalcer::DistributeRandoms (MyArray & Randoms)
Definition at line 106 of file radcalcer.cpp.
References _en, ZposGenerator::FindRandomPositions(), QperpGenerator::FindRandomQs(), ZposGenerator::GetTempsMu2s(), n, pi, qperps, and zDist.
Referenced by RadCalcerWrapper< numOfRandoms >::SetRandoms().
107 {
108   MyArray inZs( n );
109   MyArray inQs( n ), inThs( n ), temps( n ), mu2s( n );
110   MyArray qmins( 0., n ), qmaxs( n ), thmins( 0., n ), thmaxs( 2.*pi, n );
111 
112   // First, get an array of uniform random inputs for z positions
113   for (long i=0; i<n; ++i)
114     inZs[i] = Randoms[i];
115 
116   zDist.FindRandomPositions( inZs );
117   zDist.GetTempsMu2s( temps, mu2s );
118   
119   // Now get an array of uniform random inputs for qs,thetas
120   // and calculate qmaxs from medium params
121   for (long i=0; i<n; ++i)
122   {
123     inQs[i] = Randoms[i + n];
124     inThs[i] = Randoms[i + 2*n];
125     qmaxs[i] = sqrt(6.*temps[i]*_en);
126   }
127   
128   qperps.FindRandomQs( inQs, qmins, qmaxs, inThs, thmins, thmaxs, mu2s );
129 }
void RadCalcer::SetXonly (double x)
Definition at line 131 of file radcalcer.cpp.
References _dglv, _en, _frac, _mass, _mg, _overx, _x, and SwUtils::hbarc.
Referenced by RadCalcerWrapper< numOfRandoms >::SetCoord().
132 {
133   _x = x;
134   _overx = 1./x;
135 
136   _dglv = _mg*_mg*(1.-_x) + _mass*_mass*_x*_x;
137   // DeltaZi is in fm, _en is in GeV => need factor hbarc
138   _frac = 1. / (2. * _x * _en * hbarc);
139 }
void RadCalcer::SetKonly (double k)
Definition at line 141 of file radcalcer.cpp.
References _k, qperps, and QperpGenerator::SetK().
Referenced by RadCalcerWrapper< numOfRandoms >::SetCoord().
142 {
143   //k = 1.2;
144   qperps.SetK( k );
145   _k = k;
146 }
double RadCalcer::Getkmax () const [inline]
Definition at line 60 of file radcalcer.h.
References _en, _switchkmax, and _x.
Referenced by GetdNdk2dx().
61 {
62   double kmax;
63   switch (_switchkmax)
64   {
65     case 1:
66       // Ivan's first version of k_max
67       kmax = _x*_en;
68     break;
69 
70     case 2:
71       // Another version from Ivan's code
72       _x <= 0.5 ? kmax = _x*_en : kmax = (1.-_x)*_en;
73     break;
74 
75     case 3:
76       // Magdalena's favourite version of k_max
77       kmax = 2.*_x*(1.-_x)*_en;
78     break;
79 
80     default:
81       kmax = -1.;
82       break;
83   }
84   return kmax;
85 }
void RadCalcer::GetdNdk2dx (MyArray & results)
Definition at line 219 of file radcalcer.cpp.
References _alphas, _cdotb(), SwUtils::_Combinatoric(), _correlated, _cr, _diffexclude, _interferenceExp(), _k, _overx, Getkmax(), QperpGenerator::GetQeventWeight(), ZposGenerator::GetZweight(), n, overpi, SwUtils::power(), qperps, QperpGenerator::SetZeroedQs(), and zDist.
Referenced by RadCalcerWrapper< numOfRandoms >::GetAnswer().
220 {
221   // Ok, we're going to calculate dNdxdk, and fill the array 'results' with the answer
222   // results[n-1] = the full answer, the others are just intermediate stages
223 
224   // What recording scheme are we going by?
225   // If we set _maxOpac = n here, it will record the full summation, plus n subsets
226   // If we set _maxOpac = 2^n, it will record all possible subsets
227   //long _maxOpac = n;
228   //long _maxOpac = power(2,n);
229   long _maxOpac = 1;
230 
231   // If we are out of bounds of the k integral, we just return zero for all the whole result array
232   if ( _k >= Getkmax() )
233   {
234     for (long i=0; i<_maxOpac; ++i)
235       results[i] = 0.;
236     return;
237   }
238 
239   // Our intermediate stages, and our final result: result
240   double msum, qweight, zweight, coeff, result;
241   // Reset to zero, will add on terms to this
242   result = 0.;
243 
244   // If the medium is correlated, then we need to iterate over all the permutations
245   // of the delta functions under the integral.
246   // If the medium is uncorrelated, we only need to count the delta functions, not 
247   // evaluate separately from each. In this way, we save a whole lot of calculation
248   // for the uncorrelated medium.
249   // We go from 0<z<2^n to 0<z<n. Oooh, orders of magnitude performance enhancement!  
250 
251   if ( _correlated )
252   {
253     // Iterate over all terms in series from the products with the delta function subtracted off
254     // Method: count from 1 up to 2^n, the binary representation of that number - of length n -
255     // Gives a unique set of zeroed q's. If the binary digit = 1, then that q is zeroed out
256     long imin = 0;
257     long imax = power(2,n);
258     // opac is to do with what we're putting in the results matrix
259     // We will increase it as we go along. Wow, what an explanation.
260     // long opac = 1;
261 
262     // results[n-1] = 0.;
263     for (long i=imax-2; i>=imin; --i)
264     {
265       // Set the zeroed Qs for this term
266       qperps.SetZeroedQs( i );
267     
268       // Sum over all the c dot b terms
269       msum = 0.;
270       // What m value do we start at?
271       unsigned long mmin;
272       // If we want to only look at the quantum source term, exclude the classical
273       // diffusion terms, then we start at n. If we want all of it, then we start at 1.
274       _diffexclude ? mmin = n : mmin = 1;
275 
276       // This sum is defined in GLV II.
277       for (long m=mmin; m<=n; ++m)
278       {
279         // If we are in an uncorrelated medium, then we do the z integrals analytically
280         // and sum up the resulting Lorentzians. If not, then we have to do the full sum.
281 
282         //msum += -2.*_cdotb( m ) * _interference( m );
283         msum += -2.*_cdotb( m ) * _interferenceExp( m);
284       }
285 
286       // Get the q weight - we have generated random q values, but we allow
287       // for generating from a different distribution, and then moving a coefficient
288       // into the answer. See reweighted Monte-Carlo integration.
289       qweight = qperps.GetQeventWeight();
290       // Same for the z weight. Remember that we might not even be evaluating a z integral here.
291       zweight = zDist.GetZweight();
292 
293       // Now add what we have to what we had from the previous z values
294       result += qweight * zweight * msum;
295 
296       // If we are at a power of 2, put the result into our result matrix
297       //if ( i == imax-power(2,opac) )
298       //{
299       //  (n-opac)%2 == 0 ? results[opac-1] = result : results[opac-1] = -result;
300       //  ++opac;
301       //}
302     }
303     results[0] = result;
304     // We have left out a few coeffs that are the same for all evaluations.
305     // Now multiply through by them.
306     coeff = _k * _overx * overpi  *  _cr*_alphas*2.;
307     for (long i=0; i!=_maxOpac; ++i)
308     {
309       results[i] *= coeff;
310     }
311     // And we're done!
312   }
313   else
314   {
315     // We have a correlated medium. We have n separate contributions (as opposed to the 2^n for
316     // the correlated medium). In this case, z will represent how many zeroed q's we have.
317     long zmin = 0;
318     long zmax = n;
319     long combin;
320 
321     // Now iterate over the possible zeroed out q's
322     for (long z=zmax-1; z>=zmin; --z)
323     {
324       // The combinatoric factor. How many combinations? = n C z
325       combin = _Combinatoric( n, z );
326       
327       // Set the zeroed Qs for this term
328       qperps.SetZeroedQs( z );
329 
330       // Sum over all the c dot b terms
331       msum = 0.;
332       // What m value do we start at?
333       unsigned long mmin;
334       // If we want to only look at the quantum source term, exclude the classical
335       // diffusion terms, then we start at n. If we want all of it, then we start at 1.
336       _diffexclude ? mmin = n : mmin = 1;
337 
338       // This sum is defined in GLV II.
339       for (long m=mmin; m<=n; ++m)
340       {
341         // If we are in an uncorrelated medium, then we do the z integrals analytically
342         // and sum up the resulting Lorentzians. If not, then we have to do the full sum.
343 
344         //msum += -2.*_cdotb( m ) * _interference( m );
345         msum += -2.*_cdotb( m ) * _interferenceExp( m );
346       }
347 
348       // Get the q weight - we have generated random q values, but we allow
349       // for generating from a different distribution, and then moving a coefficient
350       // into the answer. See reweighted Monte-Carlo integration.
351       qweight = qperps.GetQeventWeight();
352       // Same for the z weight. Remember that we might not even be evaluating a z integral here.
353       zweight = zDist.GetZweight();
354 
355       // Now add what we have to what we had from the previous z values
356       result += qweight * zweight * msum;
357 
358       results[n-1-z] = result;
359     }
360     
361     // We have left out a few coeffs that are the same for all evaluations.
362     // Now multiply through by them.
363     coeff = _k * _overx * overpi  *  _cr*_alphas*2.;
364     for (long i=0; i!=_maxOpac; ++i)
365     {
366       results[i] *= coeff;
367     }
368     // And we're done!
369   }
370 }
Member Data Documentation
ZposGenerator RadCalcer::zDist [private]
Definition at line 14 of file radcalcer.h.
Referenced by _interference(), DistributeRandoms(), and GetdNdk2dx().
QperpGenerator RadCalcer::qperps [private]
Definition at line 15 of file radcalcer.h.
Referenced by _cdotb(), _interference(), _interferenceExp(), DistributeRandoms(), GetdNdk2dx(), and SetKonly().
const long RadCalcer::n [private]
Definition at line 17 of file radcalcer.h.
Referenced by _interferenceExp(), DistributeRandoms(), and GetdNdk2dx().
double RadCalcer::_x [private]
Definition at line 19 of file radcalcer.h.
Referenced by Getkmax(), and SetXonly().
double RadCalcer::_overx [private]
Definition at line 20 of file radcalcer.h.
Referenced by GetdNdk2dx(), and SetXonly().
double RadCalcer::_k [private]
Definition at line 21 of file radcalcer.h.
Referenced by GetdNdk2dx(), and SetKonly().
double RadCalcer::_en [private]
Definition at line 23 of file radcalcer.h.
Referenced by DistributeRandoms(), Getkmax(), RadCalcer(), and SetXonly().
double RadCalcer::_mass [private]
Definition at line 24 of file radcalcer.h.
Referenced by RadCalcer(), and SetXonly().
double RadCalcer::_cr [private]
Definition at line 25 of file radcalcer.h.
Referenced by GetdNdk2dx(), and RadCalcer().
double RadCalcer::_temp [private]
Definition at line 27 of file radcalcer.h.
double RadCalcer::_mg [private]
Definition at line 28 of file radcalcer.h.
Referenced by RadCalcer(), and SetXonly().
double RadCalcer::_lambda [private]
Definition at line 29 of file radcalcer.h.
double RadCalcer::_length [private]
Definition at line 30 of file radcalcer.h.
Referenced by _interferenceExp(), and RadCalcer().
double RadCalcer::_alphas [private]
Definition at line 32 of file radcalcer.h.
Referenced by GetdNdk2dx(), and RadCalcer().
unsigned long RadCalcer::_switchkmax [private]
Definition at line 34 of file radcalcer.h.
Referenced by Getkmax(), and RadCalcer().
double RadCalcer::_dglv [private]
Definition at line 36 of file radcalcer.h.
Referenced by _cdotb(), _interference(), _interferenceExp(), and SetXonly().
double RadCalcer::_frac [private]
Definition at line 37 of file radcalcer.h.
Referenced by _interference(), _interferenceExp(), and SetXonly().
bool RadCalcer::_correlated [private]
Definition at line 39 of file radcalcer.h.
Referenced by GetdNdk2dx(), and RadCalcer().
bool RadCalcer::_diffexclude [private]
Definition at line 40 of file radcalcer.h.
Referenced by GetdNdk2dx(), and RadCalcer().
The documentation for this class was generated from the following files:
Gyulassy/opacity3/src/glv1/radcalcer.h
Gyulassy/opacity3/src/glv1/radcalcer.cpp