YukawaFunction Class Reference
#include <Function.h>
Public Member Functions
YukawaFunction (unsigned long Dimensionality)
virtual ~YukawaFunction ()
virtual Function * clone () const
virtual void function (MyArray &xs, MyArray &res)
virtual void NormedIntegralInverse (MyArray &xs, MyArray &res)
virtual void SetParams (MyArray &params_)
Private Attributes
MyArray mu2s
Detailed Description
Definition at line 53 of file Function.h.
Constructor & Destructor Documentation
YukawaFunction::YukawaFunction (unsigned long Dimensionality)
Definition at line 22 of file Function.cpp.
Referenced by clone().
23   : Function( Dimensionality ), mu2s( Dimensionality )
24 {
25 
26 }
YukawaFunction::~YukawaFunction () [virtual]
Definition at line 28 of file Function.cpp.
29 {
30 
31 }
Member Function Documentation
Function * YukawaFunction::clone () const [virtual]
Implements Function .
Definition at line 33 of file Function.cpp.
References YukawaFunction().
34 {
35   return new YukawaFunction( *this );
36 }
void YukawaFunction::function (MyArray & xs, MyArray & res) [virtual]
Implements Function .
Definition at line 38 of file Function.cpp.
References Function::GetDimensionality(), and mu2s.
39 {
40   for (unsigned long i=0; i<GetDimensionality(); ++i)
41   {
42     res[i] = 2.*xs[i]*mu2s[i] / pow( xs[i]*xs[i] + mu2s[i], 2 );
43   }
44 }
void YukawaFunction::NormedIntegralInverse (MyArray & xs, MyArray & res) [virtual]
Implements Function .
Definition at line 46 of file Function.cpp.
References Function::GetDimensionality(), Function::GetXmax(), Function::GetXmin(), and mu2s.
47 {
48   for (unsigned long i=0; i<GetDimensionality(); ++i)
49   {
50     xs[i] = (pow(GetXmin(i),2) + mu2s[i]) * (pow(GetXmax(i),2) + mu2s[i]);
51     xs[i] /= mu2s[i] + pow(GetXmax(i),2) - (pow(GetXmax(i),2)-pow(GetXmin(i),2))*uniforms[i];
52     xs[i] -= mu2s[i];
53     xs[i] = sqrt(xs[i]);
54   }
55 }
void YukawaFunction::SetParams (MyArray & params_) [virtual]
Implements Function .
Definition at line 57 of file Function.cpp.
References mu2s.
58 {
59   mu2s = mu2s_;
60 }
Member Data Documentation
MyArray YukawaFunction::mu2s [private]
Definition at line 66 of file Function.h.
Referenced by function(), NormedIntegralInverse(), and SetParams().
The documentation for this class was generated from the following files:
Gyulassy/opacity3/src/glv1/Function.h
Gyulassy/opacity3/src/glv1/Function.cpp