Function Class Reference
#include <Function.h>
Public Member Functions
Function (unsigned long Dimensionality)
virtual ~Function ()
virtual Function * clone () const =0
virtual void function (MyArray &xs, MyArray &res)=0
virtual void NormedIntegralInverse (MyArray &xs, MyArray &res)=0
virtual void SetLimits (MyArray &xmins_, MyArray &xmaxs_)
virtual void SetParams (MyArray &params_)=0
unsigned long GetDimensionality () const
double GetXmin (unsigned long i) const
double GetXmax (unsigned long i) const
double GetRange (unsigned long i) const
Private Attributes
unsigned long dim
MyArray xmins
MyArray xmaxs
Detailed Description
Definition at line 8 of file Function.h.
Constructor & Destructor Documentation
Function::Function (unsigned long Dimensionality)
Definition at line 3 of file Function.cpp.
4   : dim( Dimensionality ), xmins( Dimensionality ), xmaxs( Dimensionality )
5 {
6 
7 }
Function::~Function () [virtual]
Definition at line 9 of file Function.cpp.
10 {
11 
12 }
Member Function Documentation
virtual Function* Function::clone () const [pure virtual]
Implemented in YukawaFunction , UniformFunction , UnitStepFunction , and ExpDecayFunction .
virtual void Function::function (MyArray & xs, MyArray & res) [pure virtual]
Implemented in YukawaFunction , UniformFunction , UnitStepFunction , and ExpDecayFunction .
virtual void Function::NormedIntegralInverse (MyArray & xs, MyArray & res) [pure virtual]
Implemented in YukawaFunction , UniformFunction , UnitStepFunction , and ExpDecayFunction .
void Function::SetLimits (MyArray & xmins_, MyArray & xmaxs_) [virtual]
Definition at line 14 of file Function.cpp.
References xmaxs, and xmins.
Referenced by ZposGenerator::ZposGenerator().
15 {
16   xmins = xmins_;
17   xmaxs = xmaxs_;
18 }
virtual void Function::SetParams (MyArray & params_) [pure virtual]
Implemented in YukawaFunction , UniformFunction , UnitStepFunction , and ExpDecayFunction .
unsigned long Function::GetDimensionality () const [inline]
Definition at line 33 of file Function.h.
References dim.
Referenced by ExpDecayFunction::function(), UnitStepFunction::function(), UniformFunction::function(), YukawaFunction::function(), ExpDecayFunction::NormedIntegralInverse(), UnitStepFunction::NormedIntegralInverse(), UniformFunction::NormedIntegralInverse(), and YukawaFunction::NormedIntegralInverse().
34 {
35   return dim;
36 }
double Function::GetXmin (unsigned long i) const [inline]
Definition at line 38 of file Function.h.
References xmins.
Referenced by ExpDecayFunction::function(), UnitStepFunction::function(), ExpDecayFunction::NormedIntegralInverse(), UnitStepFunction::NormedIntegralInverse(), UniformFunction::NormedIntegralInverse(), and YukawaFunction::NormedIntegralInverse().
39 {
40   return xmins[i];
41 }
double Function::GetXmax (unsigned long i) const [inline]
Definition at line 43 of file Function.h.
References xmaxs.
Referenced by ExpDecayFunction::NormedIntegralInverse(), and YukawaFunction::NormedIntegralInverse().
44 {
45   return xmaxs[i];
46 }
double Function::GetRange (unsigned long i) const [inline]
Definition at line 48 of file Function.h.
References xmaxs, and xmins.
Referenced by UniformFunction::function(), and UniformFunction::NormedIntegralInverse().
49 {
50   return (xmaxs[i] - xmins[i]);
51 }
Member Data Documentation
unsigned long Function::dim [private]
Definition at line 27 of file Function.h.
Referenced by GetDimensionality().
MyArray Function::xmins [private]
Definition at line 28 of file Function.h.
Referenced by GetRange(), GetXmin(), and SetLimits().
MyArray Function::xmaxs [private]
Definition at line 29 of file Function.h.
Referenced by GetRange(), GetXmax(), and SetLimits().
The documentation for this class was generated from the following files:
Gyulassy/opacity3/src/glv1/Function.h
Gyulassy/opacity3/src/glv1/Function.cpp