QperpCalculator3< n > Class Template Reference
#include <qperpcalculator3.h>
Public Member Functions
QperpCalculator3 ()
void SetK (double k)
void SetQsThetas (boost::array< double, n > Qs, boost::array< double, n > Thetas)
double GetSumQskk (long m, long zeroes) const
double GetSumQs1k (long m, long zeroes) const
Private Attributes
boost::array< boost::array< double, n >, TPower< 2, n >::value > SumQs_1i
Array of Sum_(i=1 to n, j = k to n)_Qi Dot Qj.
boost::array< boost::array< double, n >, TPower< 2, n >::value > SumQs_ii
boost::array< boost::array< double, n >, TPower< 2, n >::value > SumKhatQ_i
boost::array< boost::array< double, n+1 >, TPower< 2, n >::value > SumQsIncK_1i
boost::array< boost::array< double, n+1 >, TPower< 2, n >::value > SumQsIncK_ii
Detailed Description
template<std::size_t n> class QperpCalculator3< n >
Author:
Definition at line 34 of file qperpcalculator3.h.
Constructor & Destructor Documentation
template<std::size_t n> QperpCalculator3< n >::QperpCalculator3 () [inline]
Definition at line 64 of file qperpcalculator3.h.
65 {
66 
67 }
Member Function Documentation
template<std::size_t n> void QperpCalculator3< n >::SetK (double k) [inline]
Definition at line 70 of file qperpcalculator3.h.
References QperpCalculator3< n >::SumKhatQ_i, QperpCalculator3< n >::SumQs_1i, QperpCalculator3< n >::SumQs_ii, QperpCalculator3< n >::SumQsIncK_1i, and QperpCalculator3< n >::SumQsIncK_ii.
Referenced by main().
71 {
72   const double k2 = k*k;
73   boost::array<double, n> sumkq_i;
74   for ( long z=0; z<TPower<2,n>::value; ++z )
75   {
76     for ( std::size_t i=0; i<n; ++i )
77     {
78       sumkq_i[i] = k * SumKhatQ_i[z][i];
79       SumQsIncK_1i[z][i] = SumQs_1i[z][i] + sumkq_i[0] + sumkq_i[i] + k2;
80       SumQsIncK_ii[z][i] = SumQs_ii[z][i] + 2.*sumkq_i[i] + k2;
81     }
82     SumQsIncK_1i[z][n] = sumkq_i[0] + k2;
83     SumQsIncK_ii[z][n] = k2;
84   }
85 }
template<std::size_t n> void QperpCalculator3< n >::SetQsThetas (boost::array< double, n > Qs, boost::array< double, n > Thetas) [inline]
Definition at line 88 of file qperpcalculator3.h.
References SwUtils::_TestBitI(), QperpCalculator3< n >::SumKhatQ_i, QperpCalculator3< n >::SumQs_1i, and QperpCalculator3< n >::SumQs_ii.
Referenced by main().
90 {
91   boost::array<double, n> qxs, qys;
92   _Convert2DPolarToCartesian<n>( Qs, Thetas, qxs, qys );
93 
94   boost::array<double, n> sumqxs, sumqys;
95   bool notZeroed;
96 
97   for ( std::size_t z=0; z<TPower<2,n>::value; ++z )
98   {
99     notZeroed = !SwUtils::_TestBitI( z, 0 );
100     sumqxs[n-1] = notZeroed*qxs[n-1]; sumqys[n-1] = notZeroed*qys[n-1];
101     for ( std::size_t i=1; i<n; ++i )
102     {
103       std::size_t ind = n-1-i;
104       notZeroed = !SwUtils::_TestBitI( z, i );
105       sumqxs[ind] = sumqxs[ind+1] + notZeroed*qxs[ind];
106       sumqys[ind] = sumqys[ind+1] + notZeroed*qys[ind];
107     }
108 
109     for ( std::size_t i=0; i<n; ++i )
110     {
111       SumQs_1i[z][i] = sumqxs[0]*sumqxs[i] + sumqys[0]*sumqys[i];
112       SumQs_ii[z][i] = sumqxs[i]*sumqxs[i] + sumqys[i]*sumqys[i];
113       SumKhatQ_i[z][i] = -sumqxs[i];
114     }
115   }
116 }
template<std::size_t n> double QperpCalculator3< n >::GetSumQskk (long m, long zeroes) const [inline]
Definition at line 51 of file qperpcalculator3.h.
References QperpCalculator3< n >::SumQsIncK_ii.
Referenced by main().
52   {
53     return ( SumQsIncK_ii[zeroes][m-1] );
54   };
template<std::size_t n> double QperpCalculator3< n >::GetSumQs1k (long m, long zeroes) const [inline]
Definition at line 56 of file qperpcalculator3.h.
References QperpCalculator3< n >::SumQsIncK_1i.
Referenced by main().
57   {
58     return ( SumQsIncK_1i[zeroes][m-1] );
59   };
Member Data Documentation
template<std::size_t n> boost::array<boost::array<double, n>, TPower<2,n>::value> QperpCalculator3< n >::SumQs_1i [private]
Array of Sum_(i=1 to n, j = k to n)_Qi Dot Qj.
Definition at line 38 of file qperpcalculator3.h.
Referenced by QperpCalculator3< n >::SetK(), and QperpCalculator3< n >::SetQsThetas().
template<std::size_t n> boost::array<boost::array<double, n>, TPower<2,n>::value> QperpCalculator3< n >::SumQs_ii [private]
Definition at line 39 of file qperpcalculator3.h.
Referenced by QperpCalculator3< n >::SetK(), and QperpCalculator3< n >::SetQsThetas().
template<std::size_t n> boost::array<boost::array<double, n>, TPower<2,n>::value> QperpCalculator3< n >::SumKhatQ_i [private]
Definition at line 40 of file qperpcalculator3.h.
Referenced by QperpCalculator3< n >::SetK(), and QperpCalculator3< n >::SetQsThetas().
template<std::size_t n> boost::array<boost::array<double, n+1>, TPower<2,n>::value> QperpCalculator3< n >::SumQsIncK_1i [private]
Definition at line 42 of file qperpcalculator3.h.
Referenced by QperpCalculator3< n >::GetSumQs1k(), and QperpCalculator3< n >::SetK().
template<std::size_t n> boost::array<boost::array<double, n+1>, TPower<2,n>::value> QperpCalculator3< n >::SumQsIncK_ii [private]
Definition at line 43 of file qperpcalculator3.h.
Referenced by QperpCalculator3< n >::GetSumQskk(), and QperpCalculator3< n >::SetK().
The documentation for this class was generated from the following file:
Gyulassy/opacity3/src/glv3/qperpcalculator3.h