ExpDecayFunction Class Reference
#include <Function.h>
Public Member Functions
ExpDecayFunction (unsigned long Dimensionality)
virtual ~ExpDecayFunction ()
virtual Function * clone () const
virtual void function (MyArray &xs, MyArray &res)
virtual void NormedIntegralInverse (MyArray &xs, MyArray &res)
virtual void SetParams (MyArray &params_)
Private Attributes
MyArray lambdas
Detailed Description
Definition at line 101 of file Function.h.
Constructor & Destructor Documentation
ExpDecayFunction::ExpDecayFunction (unsigned long Dimensionality)
Definition at line 144 of file Function.cpp.
Referenced by clone().
145   : Function( Dimensionality ), lambdas( Dimensionality )
146 {
147 
148 }
ExpDecayFunction::~ExpDecayFunction () [virtual]
Definition at line 150 of file Function.cpp.
151 {
152 
153 }
Member Function Documentation
Function * ExpDecayFunction::clone () const [virtual]
Implements Function .
Definition at line 155 of file Function.cpp.
References ExpDecayFunction().
156 {
157   return new ExpDecayFunction( *this );
158 }
void ExpDecayFunction::function (MyArray & xs, MyArray & res) [virtual]
Implements Function .
Definition at line 160 of file Function.cpp.
References Function::GetDimensionality(), Function::GetXmin(), and lambdas.
161 {
162   res[0] = 1. / lambdas[0] * exp( -((xs[0]-GetXmin(0)) / lambdas[0]) );
163   for (unsigned long i=1; i<GetDimensionality(); ++i)
164   {
165     res[i] = 1. / lambdas[i] * exp( -(xs[i] - xs[i-1]) / lambdas[i] );
166   }
167 }
void ExpDecayFunction::NormedIntegralInverse (MyArray & xs, MyArray & res) [virtual]
Implements Function .
Definition at line 169 of file Function.cpp.
References Function::GetDimensionality(), Function::GetXmax(), Function::GetXmin(), and lambdas.
170 {
171   for (unsigned long i=0; i<GetDimensionality(); ++i)
172   {
173     xs[i] = (1.-uniforms[i])*exp(-GetXmin(i)/lambdas[i]) + uniforms[i]*exp(-GetXmax(i)/lambdas[i]);
174     xs[i] = -lambdas[i] * log( xs[i] );
175   }
176 }
void ExpDecayFunction::SetParams (MyArray & params_) [virtual]
Implements Function .
Definition at line 178 of file Function.cpp.
References lambdas.
Referenced by ZposGenerator::ZposGenerator().
179 {
180   lambdas = params_;
181 }
Member Data Documentation
MyArray ExpDecayFunction::lambdas [private]
Definition at line 114 of file Function.h.
Referenced by function(), NormedIntegralInverse(), and SetParams().
The documentation for this class was generated from the following files:
Gyulassy/opacity3/src/glv1/Function.h
Gyulassy/opacity3/src/glv1/Function.cpp