SwUtils Namespace Reference
Functions
long _FindNextPowerOfTwo (long value)
long _Combinatoric (long n, long r)
long _factorial (long value, long endval=1)
long power (long num, long pow)
bool _TestBitI (unsigned long num, unsigned long i)
void _NumberToBoolArray (unsigned long num, std::vector< bool > &boolarray, unsigned long length)
long _CountNumZeroes (unsigned long num, unsigned long length)
bool _IsPowerOfTwo (long value)
Variables
const double pi = 3.141592653589793238
const double overpi = 0.3183098861837906715
const double hbarc = 0.197
Function Documentation
long SwUtils::_Combinatoric (long n, long r)
Definition at line 22 of file constants.cpp.
References _factorial().
Referenced by RadCalcer::GetdNdk2dx().
23 {
24   // This returns the combinatoric factor n C r
25   // ie n! / ( (n-r)! r! )
26   // Note: sum of n C r over r gives 2^n
27 
28   if ( r >= n || r <= 0 )
29     return 1;
30 
31   // _factorial (n,b) = n!/(b-1)! ie n*(n-1)*...*b
32   return ( _factorial( n, n-r+1 ) / _factorial( r ) );
33 }
long SwUtils::_CountNumZeroes (unsigned long num, unsigned long length) [inline]
Definition at line 51 of file constants.h.
References _TestBitI().
52 {
53   long tot = 0;
54   for (unsigned long i=0; i!=length; ++i)
55   {
56     if ( _TestBitI( num, i ) )
57       ++tot;
58   }
59   return tot;
60 }
long SwUtils::_factorial (long value, long endval = 1) [inline]
Definition at line 14 of file constants.h.
Referenced by _Combinatoric(), ZposGenerator::FindRandomPositions(), and GlvRadiative3< TqperpGenerate, TqperpCalculate, numOfRandoms >::GetdNdxdk().
15 {
16   if (value > endval)
17     return ( value * _factorial( value - 1 ) );
18 
19   return endval;
20 }
long SwUtils::_FindNextPowerOfTwo (long value)
Definition at line 7 of file constants.cpp.
References _IsPowerOfTwo().
Referenced by StatGathering::ConvergenceTable::AddOneSetOfResults(), and StatGathering::ConvergenceTable::SetResultsSoFar().
8 {
9   long myreturn = 0;
10   --value;
11   do
12   {
13     ++value;
14     if ( _IsPowerOfTwo( value ) )
15       myreturn = value;
16   }
17   while( myreturn == 0 );
18 
19   return myreturn;
20 }
bool SwUtils::_IsPowerOfTwo (long value) [inline]
Definition at line 62 of file constants.h.
Referenced by _FindNextPowerOfTwo().
63 {
64   if (value < 1)
65     return false;
66 
67   return (value & (~value+1)) == value;  //~value+1 equals a two's complement -value
68 }
void SwUtils::_NumberToBoolArray (unsigned long num, std::vector< bool > & boolarray, unsigned long length) [inline]
Definition at line 43 of file constants.h.
References _TestBitI().
Referenced by _FillAllRows1D(), _FillAllRows2DSymmetric(), _Iterate1DForZeroes(), _Iterate2DForZeroes(), QperpGenerator3< n >::GetQsThetas(), and QperpGenerator::SetZeroedQs().
44 {
45   for (unsigned long i=0; i!=length; ++i)
46   {
47     boolarray[(length-1)-i] = _TestBitI( num, i );
48   }
49 }
bool SwUtils::_TestBitI (unsigned long num, unsigned long i) [inline]
Definition at line 34 of file constants.h.
Referenced by _CountNumZeroes(), _NumberToBoolArray(), and QperpCalculator3< n >::SetQsThetas().
35 {
36   int bit = ((num >> i) & 1);
37   if (bit == 1)
38     return true;
39     
40   return false;
41 }
long SwUtils::power (long num, long pow) [inline]
Definition at line 25 of file constants.h.
Referenced by RadCalcer::GetdNdk2dx(), and QperpCalculator::QperpCalculator().
26 {
27   long res = num;
28   for (long i=1; i!=pow; ++i)
29     res *= num;
30 
31   return res;
32 }
Variable Documentation
const double SwUtils::hbarc = 0.197
Definition at line 11 of file constants.h.
Referenced by RadCalcer::SetXonly().
const double SwUtils::overpi = 0.3183098861837906715
Definition at line 10 of file constants.h.
const double SwUtils::pi = 3.141592653589793238
Definition at line 9 of file constants.h.