Gyulassy/opacity3/src/glv1/qperpstore1.h File Reference
Classes
class QperpStore1
Functions
void SetZ (long zin_)
void SetVal (long x_, long y_, long val_)
double GetVal (long x_, long y_)
long XYtoIndex (long x_, long y_)
void Reset ()
Function Documentation
double GetVal (long x_, long y_)
Definition at line 80 of file qperpstore1.h.
References XYtoIndex().
81 {
82   return vals[ XYtoIndex( x_, y_ ) ];
83 }
void Reset ()
Definition at line 90 of file qperpstore1.h.
91 {
92   long imax = sizeZ * sizeXY2;
93   
94   for (long i=0; i<imax; ++i)
95     vals[i] = 0.;
96 }
void SetVal (long x_, long y_, long val_)
Definition at line 75 of file qperpstore1.h.
References XYtoIndex().
76 {
77   vals[ XYtoIndex( x_, y_ ) ] = val_;
78 }
void SetZ (long zin_)
Definition at line 70 of file qperpstore1.h.
71 {
72   bookmarkZ = sizeXY2 * zin_;
73 }
long XYtoIndex (long x_, long y_)
Definition at line 85 of file qperpstore1.h.
Referenced by GetVal(), and SetVal().
86 {
87   return ( bookmarkZ + y_*sizeXY + x_ );
88 }