Gyulassy/opacity3/src/store2d/store.cpp File Reference
#include <cmath>
#include <iostream>
#include <fstream>
#include <sstream>
#include <boost/algorithm/string.hpp>
#include `store.h`
#include `convergencetable.h`
#include `statisticsmc.h`
#include `../parameters.h`
#include `../constants.h`
Functions
std::ostream & operator<< (std::ostream &out, const Store2D &store)
std::istream & operator>> (std::istream &in, Store2D &store)
Function Documentation
std::ostream& operator<< (std::ostream & out, const Store2D & store)
Definition at line 182 of file store.cpp.
References Store2D::GetCoordDim1(), Store2D::GetCoordDim2(), Store2D::GetIndex(), Store2D::SizeDim1, Store2D::SizeDim2, Store2D::SizePerPoint, and Store2D::stats.
183 {
184   // Assume that all the preliminaries have been written
185   // All we have to do here is write the data to file / stream
186 
187   // Format: dim1 dim2 results....
188   // Incrementing dim1, then dim2
189   
190   // If there are multiple data sets per point, output one whole set then the next
191   // Hence, outer iteration is over data sets per point
192   for (long i=0; i<store.SizePerPoint; ++i)
193   {
194     // Inner iteration over all points
195     for (long dim2=0; dim2<store.SizeDim2; ++dim2)
196     {
197       for (long dim1=0; dim1<store.SizeDim1; ++dim1)
198       {
199         // First, write the k, x coords to file
200         // (for ease of reading either manually or by eg Mathematica)
201         out << store.GetCoordDim1( dim1 ) << " " << store.GetCoordDim2( dim2 ) << " ";
202         // Pass off the logic of writing to the ConvergenceTable object
203         const ConvergenceTable* conTab = static_cast<const ConvergenceTable*>
204                  ( store.stats[ store.GetIndex( dim1, dim2 ) ][i].GetConstPointer() );
205         out << *conTab;
206         out << std::endl;
207       }
208     }
209   }
210 
211   // We're done, all overloading of << has to return the supplied ostream
212   return ( out );
213 }
std::istream& operator>> (std::istream & in, Store2D & store)
Definition at line 215 of file store.cpp.
References Store2D::GetIndex(), Store2D::SizeDim1, Store2D::SizeDim2, Store2D::SizePerPoint, and Store2D::stats.
216 {
217   // TODO: improve this to handle possible alterations to the file
218   // eg blank lines, comment lines etc, handle errors and bad files properly
219 
220   double coordDim1, coordDim2;
221   // Hence, outer iteration is over data sets per point
222   for (long i=0; i<store.SizePerPoint; ++i)
223   {
224     // Inner iteration over all points
225     for (long dim2=0; dim2<store.SizeDim2; ++dim2)
226     {
227       for (long dim1=0; dim1<store.SizeDim1; ++dim1)
228       {
229         // First, we have the coords in dim1 and dim2
230         in >> coordDim1 >> coordDim2;
231         // Pass off the logic of reading to the ConvergenceTable object
232         ConvergenceTable* conTab = static_cast<ConvergenceTable*>
233                  ( store.stats[ store.GetIndex( dim1, dim2 ) ][i].GetPointer() );
234         in >> *conTab;
235       }
236     }
237   }
238 
239   return ( in );
240 }